
    #include <node.h>
    #include <SDL.h>

    void InitConstants(v8::Handle<v8::Object> target) {
    v8::HandleScope scope;

    
target->Set(v8::String::NewSymbol("SCANCODE_BACKSPACE"), v8::Integer::New(SDL_SCANCODE_BACKSPACE));
target->Set(v8::String::NewSymbol("KMOD_LALT"), v8::Integer::New(KMOD_LALT));
target->Set(v8::String::NewSymbol("WINDOWEVENT_NONE"), v8::Integer::New(SDL_WINDOWEVENT_NONE));
target->Set(v8::String::NewSymbol("K_KBDILLUMUP"), v8::Integer::New(SDLK_KBDILLUMUP));
target->Set(v8::String::NewSymbol("HAT_CENTERED"), v8::Integer::New(SDL_HAT_CENTERED));
target->Set(v8::String::NewSymbol("K_WWW"), v8::Integer::New(SDLK_WWW));
target->Set(v8::String::NewSymbol("SCANCODE_NONUSHASH"), v8::Integer::New(SDL_SCANCODE_NONUSHASH));
target->Set(v8::String::NewSymbol("CONTROLLER_AXIS_TRIGGERRIGHT"), v8::Integer::New(SDL_CONTROLLER_AXIS_TRIGGERRIGHT));
target->Set(v8::String::NewSymbol("K_KP_MEMRECALL"), v8::Integer::New(SDLK_KP_MEMRECALL));
target->Set(v8::String::NewSymbol("SCANCODE_KP_4"), v8::Integer::New(SDL_SCANCODE_KP_4));
target->Set(v8::String::NewSymbol("K_KP_PERIOD"), v8::Integer::New(SDLK_KP_PERIOD));
target->Set(v8::String::NewSymbol("SCANCODE_RETURN2"), v8::Integer::New(SDL_SCANCODE_RETURN2));
target->Set(v8::String::NewSymbol("GL_SHARE_WITH_CURRENT_CONTEXT"), v8::Integer::New(SDL_GL_SHARE_WITH_CURRENT_CONTEXT));
target->Set(v8::String::NewSymbol("K_KP_MULTIPLY"), v8::Integer::New(SDLK_KP_MULTIPLY));
target->Set(v8::String::NewSymbol("PIXELFORMAT_INDEX1MSB"), v8::Integer::New(SDL_PIXELFORMAT_INDEX1MSB));
target->Set(v8::String::NewSymbol("SCANCODE_KP_HASH"), v8::Integer::New(SDL_SCANCODE_KP_HASH));
target->Set(v8::String::NewSymbol("K_EXSEL"), v8::Integer::New(SDLK_EXSEL));
target->Set(v8::String::NewSymbol("K_QUOTEDBL"), v8::Integer::New(SDLK_QUOTEDBL));
target->Set(v8::String::NewSymbol("JOYAXISMOTION"), v8::Integer::New(SDL_JOYAXISMOTION));
target->Set(v8::String::NewSymbol("K_KP_000"), v8::Integer::New(SDLK_KP_000));
target->Set(v8::String::NewSymbol("K_KP_8"), v8::Integer::New(SDLK_KP_8));
target->Set(v8::String::NewSymbol("K_CLEARAGAIN"), v8::Integer::New(SDLK_CLEARAGAIN));
target->Set(v8::String::NewSymbol("AUDIO_ALLOW_FREQUENCY_CHANGE"), v8::Integer::New(SDL_AUDIO_ALLOW_FREQUENCY_CHANGE));
target->Set(v8::String::NewSymbol("K_MODE"), v8::Integer::New(SDLK_MODE));
target->Set(v8::String::NewSymbol("SCANCODE_COPY"), v8::Integer::New(SDL_SCANCODE_COPY));
target->Set(v8::String::NewSymbol("SCANCODE_GRAVE"), v8::Integer::New(SDL_SCANCODE_GRAVE));
target->Set(v8::String::NewSymbol("K_AC_STOP"), v8::Integer::New(SDLK_AC_STOP));
target->Set(v8::String::NewSymbol("SCANCODE_KP_2"), v8::Integer::New(SDL_SCANCODE_KP_2));
target->Set(v8::String::NewSymbol("SCANCODE_CAPSLOCK"), v8::Integer::New(SDL_SCANCODE_CAPSLOCK));
target->Set(v8::String::NewSymbol("PACKEDLAYOUT_565"), v8::Integer::New(SDL_PACKEDLAYOUT_565));
target->Set(v8::String::NewSymbol("SCANCODE_PAGEDOWN"), v8::Integer::New(SDL_SCANCODE_PAGEDOWN));
target->Set(v8::String::NewSymbol("PACKEDORDER_RGBX"), v8::Integer::New(SDL_PACKEDORDER_RGBX));
target->Set(v8::String::NewSymbol("INIT_VIDEO"), v8::Integer::New(SDL_INIT_VIDEO));
target->Set(v8::String::NewSymbol("PACKEDORDER_RGBA"), v8::Integer::New(SDL_PACKEDORDER_RGBA));
target->Set(v8::String::NewSymbol("K_AMPERSAND"), v8::Integer::New(SDLK_AMPERSAND));
target->Set(v8::String::NewSymbol("INPUTWHEEL"), v8::Integer::New(SDL_INPUTWHEEL));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGB565"), v8::Integer::New(SDL_PIXELFORMAT_RGB565));
target->Set(v8::String::NewSymbol("CONTROLLERAXISMOTION"), v8::Integer::New(SDL_CONTROLLERAXISMOTION));
target->Set(v8::String::NewSymbol("SCANCODE_STOP"), v8::Integer::New(SDL_SCANCODE_STOP));
target->Set(v8::String::NewSymbol("K_KP_0"), v8::Integer::New(SDLK_KP_0));
target->Set(v8::String::NewSymbol("SCANCODE_KP_9"), v8::Integer::New(SDL_SCANCODE_KP_9));
target->Set(v8::String::NewSymbol("SCANCODE_THOUSANDSSEPARATOR"), v8::Integer::New(SDL_SCANCODE_THOUSANDSSEPARATOR));
target->Set(v8::String::NewSymbol("BUTTON_X1"), v8::Integer::New(SDL_BUTTON_X1));
target->Set(v8::String::NewSymbol("BUTTON_X2"), v8::Integer::New(SDL_BUTTON_X2));
target->Set(v8::String::NewSymbol("IGNORE"), v8::Integer::New(SDL_IGNORE));
target->Set(v8::String::NewSymbol("ARRAYORDER_ARGB"), v8::Integer::New(SDL_ARRAYORDER_ARGB));
target->Set(v8::String::NewSymbol("WINDOWEVENT_MAXIMIZED"), v8::Integer::New(SDL_WINDOWEVENT_MAXIMIZED));
target->Set(v8::String::NewSymbol("PACKEDLAYOUT_1010102"), v8::Integer::New(SDL_PACKEDLAYOUT_1010102));
target->Set(v8::String::NewSymbol("GL_GREEN_SIZE"), v8::Integer::New(SDL_GL_GREEN_SIZE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_PLUSMINUS"), v8::Integer::New(SDL_SCANCODE_KP_PLUSMINUS));
target->Set(v8::String::NewSymbol("SCANCODE_KP_LEFTPAREN"), v8::Integer::New(SDL_SCANCODE_KP_LEFTPAREN));
target->Set(v8::String::NewSymbol("UNSUPPORTED"), v8::Integer::New(SDL_UNSUPPORTED));
target->Set(v8::String::NewSymbol("SCANCODE_SLEEP"), v8::Integer::New(SDL_SCANCODE_SLEEP));
target->Set(v8::String::NewSymbol("K_VOLUMEUP"), v8::Integer::New(SDLK_VOLUMEUP));
target->Set(v8::String::NewSymbol("HAT_RIGHT"), v8::Integer::New(SDL_HAT_RIGHT));
target->Set(v8::String::NewSymbol("K_KP_CLEARENTRY"), v8::Integer::New(SDLK_KP_CLEARENTRY));
target->Set(v8::String::NewSymbol("QUERY"), v8::Integer::New(SDL_QUERY));
target->Set(v8::String::NewSymbol("SCANCODE_SEPARATOR"), v8::Integer::New(SDL_SCANCODE_SEPARATOR));
target->Set(v8::String::NewSymbol("K_RIGHTBRACKET"), v8::Integer::New(SDLK_RIGHTBRACKET));
target->Set(v8::String::NewSymbol("K_SEMICOLON"), v8::Integer::New(SDLK_SEMICOLON));
target->Set(v8::String::NewSymbol("QUIT"), v8::Integer::New(SDL_QUIT));
target->Set(v8::String::NewSymbol("K_F8"), v8::Integer::New(SDLK_F8));
target->Set(v8::String::NewSymbol("GL_CONTEXT_FLAGS"), v8::Integer::New(SDL_GL_CONTEXT_FLAGS));
target->Set(v8::String::NewSymbol("SCANCODE_CUT"), v8::Integer::New(SDL_SCANCODE_CUT));
target->Set(v8::String::NewSymbol("K_KP_MEMDIVIDE"), v8::Integer::New(SDLK_KP_MEMDIVIDE));
target->Set(v8::String::NewSymbol("SCANCODE_MAIL"), v8::Integer::New(SDL_SCANCODE_MAIL));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED10"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED10));
target->Set(v8::String::NewSymbol("WINDOWEVENT"), v8::Integer::New(SDL_WINDOWEVENT));
target->Set(v8::String::NewSymbol("SCANCODE_EJECT"), v8::Integer::New(SDL_SCANCODE_EJECT));
target->Set(v8::String::NewSymbol("DISABLE"), v8::Integer::New(SDL_DISABLE));
target->Set(v8::String::NewSymbol("PIXELFORMAT_BGRA8888"), v8::Integer::New(SDL_PIXELFORMAT_BGRA8888));
target->Set(v8::String::NewSymbol("SCANCODE_9"), v8::Integer::New(SDL_SCANCODE_9));
target->Set(v8::String::NewSymbol("SCANCODE_8"), v8::Integer::New(SDL_SCANCODE_8));
target->Set(v8::String::NewSymbol("KEYUP"), v8::Integer::New(SDL_KEYUP));
target->Set(v8::String::NewSymbol("SCANCODE_5"), v8::Integer::New(SDL_SCANCODE_5));
target->Set(v8::String::NewSymbol("SCANCODE_4"), v8::Integer::New(SDL_SCANCODE_4));
target->Set(v8::String::NewSymbol("SCANCODE_7"), v8::Integer::New(SDL_SCANCODE_7));
target->Set(v8::String::NewSymbol("SCANCODE_6"), v8::Integer::New(SDL_SCANCODE_6));
target->Set(v8::String::NewSymbol("SCANCODE_1"), v8::Integer::New(SDL_SCANCODE_1));
target->Set(v8::String::NewSymbol("SCANCODE_0"), v8::Integer::New(SDL_SCANCODE_0));
target->Set(v8::String::NewSymbol("SCANCODE_3"), v8::Integer::New(SDL_SCANCODE_3));
target->Set(v8::String::NewSymbol("SCANCODE_2"), v8::Integer::New(SDL_SCANCODE_2));
target->Set(v8::String::NewSymbol("SCANCODE_M"), v8::Integer::New(SDL_SCANCODE_M));
target->Set(v8::String::NewSymbol("SCANCODE_L"), v8::Integer::New(SDL_SCANCODE_L));
target->Set(v8::String::NewSymbol("SCANCODE_O"), v8::Integer::New(SDL_SCANCODE_O));
target->Set(v8::String::NewSymbol("SCANCODE_N"), v8::Integer::New(SDL_SCANCODE_N));
target->Set(v8::String::NewSymbol("SCANCODE_I"), v8::Integer::New(SDL_SCANCODE_I));
target->Set(v8::String::NewSymbol("SCANCODE_H"), v8::Integer::New(SDL_SCANCODE_H));
target->Set(v8::String::NewSymbol("SCANCODE_K"), v8::Integer::New(SDL_SCANCODE_K));
target->Set(v8::String::NewSymbol("SCANCODE_J"), v8::Integer::New(SDL_SCANCODE_J));
target->Set(v8::String::NewSymbol("SCANCODE_E"), v8::Integer::New(SDL_SCANCODE_E));
target->Set(v8::String::NewSymbol("ASSERTION_BREAK"), v8::Integer::New(SDL_ASSERTION_BREAK));
target->Set(v8::String::NewSymbol("SCANCODE_G"), v8::Integer::New(SDL_SCANCODE_G));
target->Set(v8::String::NewSymbol("SCANCODE_F"), v8::Integer::New(SDL_SCANCODE_F));
target->Set(v8::String::NewSymbol("SCANCODE_A"), v8::Integer::New(SDL_SCANCODE_A));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_SIZEALL"), v8::Integer::New(SDL_SYSTEM_CURSOR_SIZEALL));
target->Set(v8::String::NewSymbol("SCANCODE_C"), v8::Integer::New(SDL_SCANCODE_C));
target->Set(v8::String::NewSymbol("SCANCODE_B"), v8::Integer::New(SDL_SCANCODE_B));
target->Set(v8::String::NewSymbol("SCANCODE_Y"), v8::Integer::New(SDL_SCANCODE_Y));
target->Set(v8::String::NewSymbol("SCANCODE_X"), v8::Integer::New(SDL_SCANCODE_X));
target->Set(v8::String::NewSymbol("MOUSEWHEEL"), v8::Integer::New(SDL_MOUSEWHEEL));
target->Set(v8::String::NewSymbol("SCANCODE_Z"), v8::Integer::New(SDL_SCANCODE_Z));
target->Set(v8::String::NewSymbol("SCANCODE_U"), v8::Integer::New(SDL_SCANCODE_U));
target->Set(v8::String::NewSymbol("SCANCODE_T"), v8::Integer::New(SDL_SCANCODE_T));
target->Set(v8::String::NewSymbol("SCANCODE_W"), v8::Integer::New(SDL_SCANCODE_W));
target->Set(v8::String::NewSymbol("MAX_LOG_MESSAGE"), v8::Integer::New(SDL_MAX_LOG_MESSAGE));
target->Set(v8::String::NewSymbol("AUDIO_ALLOW_ANY_CHANGE"), v8::Integer::New(SDL_AUDIO_ALLOW_ANY_CHANGE));
target->Set(v8::String::NewSymbol("SCANCODE_R"), v8::Integer::New(SDL_SCANCODE_R));
target->Set(v8::String::NewSymbol("GL_RED_SIZE"), v8::Integer::New(SDL_GL_RED_SIZE));
target->Set(v8::String::NewSymbol("K_KP_HASH"), v8::Integer::New(SDLK_KP_HASH));
target->Set(v8::String::NewSymbol("PIXELFORMAT_BGR888"), v8::Integer::New(SDL_PIXELFORMAT_BGR888));
target->Set(v8::String::NewSymbol("PIXELTYPE_UNKNOWN"), v8::Integer::New(SDL_PIXELTYPE_UNKNOWN));
target->Set(v8::String::NewSymbol("SCANCODE_AUDIOPLAY"), v8::Integer::New(SDL_SCANCODE_AUDIOPLAY));
target->Set(v8::String::NewSymbol("SCANCODE_PASTE"), v8::Integer::New(SDL_SCANCODE_PASTE));
target->Set(v8::String::NewSymbol("MESSAGEBOX_COLOR_MAX"), v8::Integer::New(SDL_MESSAGEBOX_COLOR_MAX));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_SYSTEM"), v8::Integer::New(SDL_LOG_CATEGORY_SYSTEM));
target->Set(v8::String::NewSymbol("BUTTON_RIGHT"), v8::Integer::New(SDL_BUTTON_RIGHT));
target->Set(v8::String::NewSymbol("K_DELETE"), v8::Integer::New(SDLK_DELETE));
target->Set(v8::String::NewSymbol("WINDOW_INPUT_GRABBED"), v8::Integer::New(SDL_WINDOW_INPUT_GRABBED));
target->Set(v8::String::NewSymbol("AUDIO_MASK_ENDIAN"), v8::Integer::New(SDL_AUDIO_MASK_ENDIAN));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_X"), v8::Integer::New(SDL_CONTROLLER_BUTTON_X));
target->Set(v8::String::NewSymbol("K_KP_LEFTPAREN"), v8::Integer::New(SDLK_KP_LEFTPAREN));
target->Set(v8::String::NewSymbol("PIXELFORMAT_BGR24"), v8::Integer::New(SDL_PIXELFORMAT_BGR24));
target->Set(v8::String::NewSymbol("K_KP_AT"), v8::Integer::New(SDLK_KP_AT));
target->Set(v8::String::NewSymbol("POWERSTATE_NO_BATTERY"), v8::Integer::New(SDL_POWERSTATE_NO_BATTERY));
target->Set(v8::String::NewSymbol("SCANCODE_COMMA"), v8::Integer::New(SDL_SCANCODE_COMMA));
target->Set(v8::String::NewSymbol("SCANCODE_NUMLOCKCLEAR"), v8::Integer::New(SDL_SCANCODE_NUMLOCKCLEAR));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_B"), v8::Integer::New(SDL_CONTROLLER_BUTTON_B));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_A"), v8::Integer::New(SDL_CONTROLLER_BUTTON_A));
target->Set(v8::String::NewSymbol("SCANCODE_MINUS"), v8::Integer::New(SDL_SCANCODE_MINUS));
target->Set(v8::String::NewSymbol("INPUTMOTION"), v8::Integer::New(SDL_INPUTMOTION));
target->Set(v8::String::NewSymbol("ASSERT_LEVEL"), v8::Integer::New(SDL_ASSERT_LEVEL));
target->Set(v8::String::NewSymbol("K_ASTERISK"), v8::Integer::New(SDLK_ASTERISK));
target->Set(v8::String::NewSymbol("BUTTON_RMASK"), v8::Integer::New(SDL_BUTTON_RMASK));
target->Set(v8::String::NewSymbol("ENOMEM"), v8::Integer::New(SDL_ENOMEM));
target->Set(v8::String::NewSymbol("K_HOME"), v8::Integer::New(SDLK_HOME));
target->Set(v8::String::NewSymbol("SCANCODE_KP_PERIOD"), v8::Integer::New(SDL_SCANCODE_KP_PERIOD));
target->Set(v8::String::NewSymbol("CONTROLLER_AXIS_MAX"), v8::Integer::New(SDL_CONTROLLER_AXIS_MAX));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_DPAD_DOWN"), v8::Integer::New(SDL_CONTROLLER_BUTTON_DPAD_DOWN));
target->Set(v8::String::NewSymbol("K_MINUS"), v8::Integer::New(SDLK_MINUS));
target->Set(v8::String::NewSymbol("PACKEDLAYOUT_2101010"), v8::Integer::New(SDL_PACKEDLAYOUT_2101010));
target->Set(v8::String::NewSymbol("SCANCODE_KP_SPACE"), v8::Integer::New(SDL_SCANCODE_KP_SPACE));
target->Set(v8::String::NewSymbol("EFSEEK"), v8::Integer::New(SDL_EFSEEK));
target->Set(v8::String::NewSymbol("K_BRIGHTNESSUP"), v8::Integer::New(SDLK_BRIGHTNESSUP));
target->Set(v8::String::NewSymbol("K_ALTERASE"), v8::Integer::New(SDLK_ALTERASE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_PERCENT"), v8::Integer::New(SDL_SCANCODE_KP_PERCENT));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_ERROR"), v8::Integer::New(SDL_LOG_CATEGORY_ERROR));
target->Set(v8::String::NewSymbol("SCANCODE_KP_MEMCLEAR"), v8::Integer::New(SDL_SCANCODE_KP_MEMCLEAR));
target->Set(v8::String::NewSymbol("WINDOW_RESIZABLE"), v8::Integer::New(SDL_WINDOW_RESIZABLE));
target->Set(v8::String::NewSymbol("K_EJECT"), v8::Integer::New(SDLK_EJECT));
target->Set(v8::String::NewSymbol("WINDOWPOS_CENTERED"), v8::Integer::New(SDL_WINDOWPOS_CENTERED));
target->Set(v8::String::NewSymbol("NUM_SCANCODES"), v8::Integer::New(SDL_NUM_SCANCODES));
target->Set(v8::String::NewSymbol("K_SLEEP"), v8::Integer::New(SDLK_SLEEP));
target->Set(v8::String::NewSymbol("MINOR_VERSION"), v8::Integer::New(SDL_MINOR_VERSION));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_ARROW"), v8::Integer::New(SDL_SYSTEM_CURSOR_ARROW));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGB444"), v8::Integer::New(SDL_PIXELFORMAT_RGB444));
target->Set(v8::String::NewSymbol("SCANCODE_AC_STOP"), v8::Integer::New(SDL_SCANCODE_AC_STOP));
target->Set(v8::String::NewSymbol("ICONV_EILSEQ"), v8::Integer::New(SDL_ICONV_EILSEQ));
target->Set(v8::String::NewSymbol("K_7"), v8::Integer::New(SDLK_7));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_INPUT"), v8::Integer::New(SDL_LOG_CATEGORY_INPUT));
target->Set(v8::String::NewSymbol("SCANCODE_KP_VERTICALBAR"), v8::Integer::New(SDL_SCANCODE_KP_VERTICALBAR));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_INVALID"), v8::Integer::New(SDL_CONTROLLER_BUTTON_INVALID));
target->Set(v8::String::NewSymbol("SCANCODE_OUT"), v8::Integer::New(SDL_SCANCODE_OUT));
target->Set(v8::String::NewSymbol("PIXELFORMAT_ABGR4444"), v8::Integer::New(SDL_PIXELFORMAT_ABGR4444));
target->Set(v8::String::NewSymbol("SCANCODE_S"), v8::Integer::New(SDL_SCANCODE_S));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_RIGHTSTICK"), v8::Integer::New(SDL_CONTROLLER_BUTTON_RIGHTSTICK));
target->Set(v8::String::NewSymbol("K_KP_MEMSTORE"), v8::Integer::New(SDLK_KP_MEMSTORE));
target->Set(v8::String::NewSymbol("K_UP"), v8::Integer::New(SDLK_UP));
target->Set(v8::String::NewSymbol("FALSE"), v8::Integer::New(SDL_FALSE));
target->Set(v8::String::NewSymbol("WINDOW_MINIMIZED"), v8::Integer::New(SDL_WINDOW_MINIMIZED));
target->Set(v8::String::NewSymbol("SCANCODE_APOSTROPHE"), v8::Integer::New(SDL_SCANCODE_APOSTROPHE));
target->Set(v8::String::NewSymbol("K_THOUSANDSSEPARATOR"), v8::Integer::New(SDLK_THOUSANDSSEPARATOR));
target->Set(v8::String::NewSymbol("SCANCODE_F5"), v8::Integer::New(SDL_SCANCODE_F5));
target->Set(v8::String::NewSymbol("PIXELFORMAT_ABGR1555"), v8::Integer::New(SDL_PIXELFORMAT_ABGR1555));
target->Set(v8::String::NewSymbol("K_LEFT"), v8::Integer::New(SDLK_LEFT));
target->Set(v8::String::NewSymbol("SCANCODE_AC_FORWARD"), v8::Integer::New(SDL_SCANCODE_AC_FORWARD));
target->Set(v8::String::NewSymbol("PIXELFORMAT_INDEX4MSB"), v8::Integer::New(SDL_PIXELFORMAT_INDEX4MSB));
target->Set(v8::String::NewSymbol("RLEACCEL"), v8::Integer::New(SDL_RLEACCEL));
target->Set(v8::String::NewSymbol("SCANCODE_KP_BACKSPACE"), v8::Integer::New(SDL_SCANCODE_KP_BACKSPACE));
target->Set(v8::String::NewSymbol("BUTTON_LMASK"), v8::Integer::New(SDL_BUTTON_LMASK));
target->Set(v8::String::NewSymbol("K_F2"), v8::Integer::New(SDLK_F2));
target->Set(v8::String::NewSymbol("K_F9"), v8::Integer::New(SDLK_F9));
target->Set(v8::String::NewSymbol("JOYDEVICEREMOVED"), v8::Integer::New(SDL_JOYDEVICEREMOVED));
target->Set(v8::String::NewSymbol("K_KP_RIGHTPAREN"), v8::Integer::New(SDLK_KP_RIGHTPAREN));
target->Set(v8::String::NewSymbol("PIXELFORMAT_YV12"), v8::Integer::New(SDL_PIXELFORMAT_YV12));
target->Set(v8::String::NewSymbol("K_F1"), v8::Integer::New(SDLK_F1));
target->Set(v8::String::NewSymbol("PACKEDORDER_BGRX"), v8::Integer::New(SDL_PACKEDORDER_BGRX));
target->Set(v8::String::NewSymbol("K_F3"), v8::Integer::New(SDLK_F3));
target->Set(v8::String::NewSymbol("K_F4"), v8::Integer::New(SDLK_F4));
target->Set(v8::String::NewSymbol("K_F5"), v8::Integer::New(SDLK_F5));
target->Set(v8::String::NewSymbol("K_F6"), v8::Integer::New(SDLK_F6));
target->Set(v8::String::NewSymbol("K_F7"), v8::Integer::New(SDLK_F7));
target->Set(v8::String::NewSymbol("PACKEDORDER_BGRA"), v8::Integer::New(SDL_PACKEDORDER_BGRA));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_WAITARROW"), v8::Integer::New(SDL_SYSTEM_CURSOR_WAITARROW));
target->Set(v8::String::NewSymbol("K_CALCULATOR"), v8::Integer::New(SDLK_CALCULATOR));
target->Set(v8::String::NewSymbol("K_KP_00"), v8::Integer::New(SDLK_KP_00));
target->Set(v8::String::NewSymbol("K_KP_OCTAL"), v8::Integer::New(SDLK_KP_OCTAL));
target->Set(v8::String::NewSymbol("SCANCODE_KP_DBLAMPERSAND"), v8::Integer::New(SDL_SCANCODE_KP_DBLAMPERSAND));
target->Set(v8::String::NewSymbol("INIT_HAPTIC"), v8::Integer::New(SDL_INIT_HAPTIC));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_MAX"), v8::Integer::New(SDL_CONTROLLER_BUTTON_MAX));
target->Set(v8::String::NewSymbol("SCANCODE_PERIOD"), v8::Integer::New(SDL_SCANCODE_PERIOD));
target->Set(v8::String::NewSymbol("SCANCODE_LEFTBRACKET"), v8::Integer::New(SDL_SCANCODE_LEFTBRACKET));
target->Set(v8::String::NewSymbol("SCANCODE_AGAIN"), v8::Integer::New(SDL_SCANCODE_AGAIN));
target->Set(v8::String::NewSymbol("SCANCODE_PRINTSCREEN"), v8::Integer::New(SDL_SCANCODE_PRINTSCREEN));
target->Set(v8::String::NewSymbol("EFWRITE"), v8::Integer::New(SDL_EFWRITE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_MEMRECALL"), v8::Integer::New(SDL_SCANCODE_KP_MEMRECALL));
target->Set(v8::String::NewSymbol("SCANCODE_COMPUTER"), v8::Integer::New(SDL_SCANCODE_COMPUTER));
target->Set(v8::String::NewSymbol("HAT_RIGHTUP"), v8::Integer::New(SDL_HAT_RIGHTUP));
target->Set(v8::String::NewSymbol("K_STOP"), v8::Integer::New(SDLK_STOP));
target->Set(v8::String::NewSymbol("MESSAGEBOX_COLOR_BUTTON_BORDER"), v8::Integer::New(SDL_MESSAGEBOX_COLOR_BUTTON_BORDER));
target->Set(v8::String::NewSymbol("JOYHATMOTION"), v8::Integer::New(SDL_JOYHATMOTION));
target->Set(v8::String::NewSymbol("JOYBALLMOTION"), v8::Integer::New(SDL_JOYBALLMOTION));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_SIZENWSE"), v8::Integer::New(SDL_SYSTEM_CURSOR_SIZENWSE));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_SIZENS"), v8::Integer::New(SDL_SYSTEM_CURSOR_SIZENS));
target->Set(v8::String::NewSymbol("K_CARET"), v8::Integer::New(SDLK_CARET));
target->Set(v8::String::NewSymbol("SCANCODE_MENU"), v8::Integer::New(SDL_SCANCODE_MENU));
target->Set(v8::String::NewSymbol("SCANCODE_AC_REFRESH"), v8::Integer::New(SDL_SCANCODE_AC_REFRESH));
target->Set(v8::String::NewSymbol("BYTEORDER"), v8::Integer::New(SDL_BYTEORDER));
target->Set(v8::String::NewSymbol("LOG_PRIORITY_CRITICAL"), v8::Integer::New(SDL_LOG_PRIORITY_CRITICAL));
target->Set(v8::String::NewSymbol("GETEVENT"), v8::Integer::New(SDL_GETEVENT));
target->Set(v8::String::NewSymbol("SCANCODE_CALCULATOR"), v8::Integer::New(SDL_SCANCODE_CALCULATOR));
target->Set(v8::String::NewSymbol("PIXELFORMAT_IYUV"), v8::Integer::New(SDL_PIXELFORMAT_IYUV));
target->Set(v8::String::NewSymbol("K_INSERT"), v8::Integer::New(SDLK_INSERT));
target->Set(v8::String::NewSymbol("CONTROLLER_AXIS_RIGHTY"), v8::Integer::New(SDL_CONTROLLER_AXIS_RIGHTY));
target->Set(v8::String::NewSymbol("SCANCODE_KP_COLON"), v8::Integer::New(SDL_SCANCODE_KP_COLON));
target->Set(v8::String::NewSymbol("SCANCODE_KP_RIGHTBRACE"), v8::Integer::New(SDL_SCANCODE_KP_RIGHTBRACE));
target->Set(v8::String::NewSymbol("SCANCODE_F3"), v8::Integer::New(SDL_SCANCODE_F3));
target->Set(v8::String::NewSymbol("WINDOW_INPUT_FOCUS"), v8::Integer::New(SDL_WINDOW_INPUT_FOCUS));
target->Set(v8::String::NewSymbol("SCANCODE_KP_DECIMAL"), v8::Integer::New(SDL_SCANCODE_KP_DECIMAL));
target->Set(v8::String::NewSymbol("HAT_DOWN"), v8::Integer::New(SDL_HAT_DOWN));
target->Set(v8::String::NewSymbol("AUDIO_MASK_DATATYPE"), v8::Integer::New(SDL_AUDIO_MASK_DATATYPE));
target->Set(v8::String::NewSymbol("K_LESS"), v8::Integer::New(SDLK_LESS));
target->Set(v8::String::NewSymbol("SCANCODE_RCTRL"), v8::Integer::New(SDL_SCANCODE_RCTRL));
target->Set(v8::String::NewSymbol("K_SLASH"), v8::Integer::New(SDLK_SLASH));
target->Set(v8::String::NewSymbol("AUDIO_ALLOW_FORMAT_CHANGE"), v8::Integer::New(SDL_AUDIO_ALLOW_FORMAT_CHANGE));
target->Set(v8::String::NewSymbol("K_RCTRL"), v8::Integer::New(SDLK_RCTRL));
target->Set(v8::String::NewSymbol("BUTTON_MIDDLE"), v8::Integer::New(SDL_BUTTON_MIDDLE));
target->Set(v8::String::NewSymbol("K_PASTE"), v8::Integer::New(SDLK_PASTE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_OCTAL"), v8::Integer::New(SDL_SCANCODE_KP_OCTAL));
target->Set(v8::String::NewSymbol("SCANCODE_F24"), v8::Integer::New(SDL_SCANCODE_F24));
target->Set(v8::String::NewSymbol("BLENDMODE_ADD"), v8::Integer::New(SDL_BLENDMODE_ADD));
target->Set(v8::String::NewSymbol("SCANCODE_F23"), v8::Integer::New(SDL_SCANCODE_F23));
target->Set(v8::String::NewSymbol("SCANCODE_F22"), v8::Integer::New(SDL_SCANCODE_F22));
target->Set(v8::String::NewSymbol("SCANCODE_F20"), v8::Integer::New(SDL_SCANCODE_F20));
target->Set(v8::String::NewSymbol("SCANCODE_PAGEUP"), v8::Integer::New(SDL_SCANCODE_PAGEUP));
target->Set(v8::String::NewSymbol("WINDOW_FULLSCREEN_DESKTOP"), v8::Integer::New(SDL_WINDOW_FULLSCREEN_DESKTOP));
target->Set(v8::String::NewSymbol("SCANCODE_LALT"), v8::Integer::New(SDL_SCANCODE_LALT));
target->Set(v8::String::NewSymbol("SCANCODE_HELP"), v8::Integer::New(SDL_SCANCODE_HELP));
target->Set(v8::String::NewSymbol("K_AUDIONEXT"), v8::Integer::New(SDLK_AUDIONEXT));
target->Set(v8::String::NewSymbol("INPUTPROXIMITYIN"), v8::Integer::New(SDL_INPUTPROXIMITYIN));
target->Set(v8::String::NewSymbol("SCANCODE_ESCAPE"), v8::Integer::New(SDL_SCANCODE_ESCAPE));
target->Set(v8::String::NewSymbol("K_KBDILLUMDOWN"), v8::Integer::New(SDLK_KBDILLUMDOWN));
target->Set(v8::String::NewSymbol("K_HASH"), v8::Integer::New(SDLK_HASH));
target->Set(v8::String::NewSymbol("SCANCODE_RETURN"), v8::Integer::New(SDL_SCANCODE_RETURN));
target->Set(v8::String::NewSymbol("BLENDMODE_MOD"), v8::Integer::New(SDL_BLENDMODE_MOD));
target->Set(v8::String::NewSymbol("SCANCODE_LEFT"), v8::Integer::New(SDL_SCANCODE_LEFT));
target->Set(v8::String::NewSymbol("CONTROLLER_BINDTYPE_NONE"), v8::Integer::New(SDL_CONTROLLER_BINDTYPE_NONE));
target->Set(v8::String::NewSymbol("COMPILEDVERSION"), v8::Integer::New(SDL_COMPILEDVERSION));
target->Set(v8::String::NewSymbol("SCANCODE_FIND"), v8::Integer::New(SDL_SCANCODE_FIND));
target->Set(v8::String::NewSymbol("SCANCODE_RGUI"), v8::Integer::New(SDL_SCANCODE_RGUI));
target->Set(v8::String::NewSymbol("GL_ACCUM_ALPHA_SIZE"), v8::Integer::New(SDL_GL_ACCUM_ALPHA_SIZE));
target->Set(v8::String::NewSymbol("K_KP_MEMMULTIPLY"), v8::Integer::New(SDLK_KP_MEMMULTIPLY));
target->Set(v8::String::NewSymbol("SCANCODE_NONUSBACKSLASH"), v8::Integer::New(SDL_SCANCODE_NONUSBACKSLASH));
target->Set(v8::String::NewSymbol("POWERSTATE_CHARGED"), v8::Integer::New(SDL_POWERSTATE_CHARGED));
target->Set(v8::String::NewSymbol("K_MEDIASELECT"), v8::Integer::New(SDLK_MEDIASELECT));
target->Set(v8::String::NewSymbol("K_AGAIN"), v8::Integer::New(SDLK_AGAIN));
target->Set(v8::String::NewSymbol("K_KP_SPACE"), v8::Integer::New(SDLK_KP_SPACE));
target->Set(v8::String::NewSymbol("K_F24"), v8::Integer::New(SDLK_F24));
target->Set(v8::String::NewSymbol("K_F23"), v8::Integer::New(SDLK_F23));
target->Set(v8::String::NewSymbol("K_F22"), v8::Integer::New(SDLK_F22));
target->Set(v8::String::NewSymbol("K_F21"), v8::Integer::New(SDLK_F21));
target->Set(v8::String::NewSymbol("K_F20"), v8::Integer::New(SDLK_F20));
target->Set(v8::String::NewSymbol("FLIP_HORIZONTAL"), v8::Integer::New(SDL_FLIP_HORIZONTAL));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_CUSTOM"), v8::Integer::New(SDL_LOG_CATEGORY_CUSTOM));
target->Set(v8::String::NewSymbol("MUTEX_MAXWAIT"), v8::Integer::New(SDL_MUTEX_MAXWAIT));
target->Set(v8::String::NewSymbol("K_KP_EXCLAM"), v8::Integer::New(SDLK_KP_EXCLAM));
target->Set(v8::String::NewSymbol("K_EXECUTE"), v8::Integer::New(SDLK_EXECUTE));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGBA8888"), v8::Integer::New(SDL_PIXELFORMAT_RGBA8888));
target->Set(v8::String::NewSymbol("SCANCODE_KP_5"), v8::Integer::New(SDL_SCANCODE_KP_5));
target->Set(v8::String::NewSymbol("SCANCODE_KP_6"), v8::Integer::New(SDL_SCANCODE_KP_6));
target->Set(v8::String::NewSymbol("SCANCODE_KP_7"), v8::Integer::New(SDL_SCANCODE_KP_7));
target->Set(v8::String::NewSymbol("SCANCODE_KP_0"), v8::Integer::New(SDL_SCANCODE_KP_0));
target->Set(v8::String::NewSymbol("SCANCODE_KP_1"), v8::Integer::New(SDL_SCANCODE_KP_1));
target->Set(v8::String::NewSymbol("ICONV_E2BIG"), v8::Integer::New(SDL_ICONV_E2BIG));
target->Set(v8::String::NewSymbol("SCANCODE_KP_3"), v8::Integer::New(SDL_SCANCODE_KP_3));
target->Set(v8::String::NewSymbol("K_KP_4"), v8::Integer::New(SDLK_KP_4));
target->Set(v8::String::NewSymbol("K_KP_5"), v8::Integer::New(SDLK_KP_5));
target->Set(v8::String::NewSymbol("K_KP_6"), v8::Integer::New(SDLK_KP_6));
target->Set(v8::String::NewSymbol("K_KP_7"), v8::Integer::New(SDLK_KP_7));
target->Set(v8::String::NewSymbol("SCANCODE_KP_8"), v8::Integer::New(SDL_SCANCODE_KP_8));
target->Set(v8::String::NewSymbol("GL_MULTISAMPLEBUFFERS"), v8::Integer::New(SDL_GL_MULTISAMPLEBUFFERS));
target->Set(v8::String::NewSymbol("SCANCODE_SLASH"), v8::Integer::New(SDL_SCANCODE_SLASH));
target->Set(v8::String::NewSymbol("K_KP_3"), v8::Integer::New(SDLK_KP_3));
target->Set(v8::String::NewSymbol("SCANCODE_KP_D"), v8::Integer::New(SDL_SCANCODE_KP_D));
target->Set(v8::String::NewSymbol("SCANCODE_KP_E"), v8::Integer::New(SDL_SCANCODE_KP_E));
target->Set(v8::String::NewSymbol("SCANCODE_KP_F"), v8::Integer::New(SDL_SCANCODE_KP_F));
target->Set(v8::String::NewSymbol("SCANCODE_KP_A"), v8::Integer::New(SDL_SCANCODE_KP_A));
target->Set(v8::String::NewSymbol("SCANCODE_KP_B"), v8::Integer::New(SDL_SCANCODE_KP_B));
target->Set(v8::String::NewSymbol("SCANCODE_KP_C"), v8::Integer::New(SDL_SCANCODE_KP_C));
target->Set(v8::String::NewSymbol("K_KP_D"), v8::Integer::New(SDLK_KP_D));
target->Set(v8::String::NewSymbol("K_KP_E"), v8::Integer::New(SDLK_KP_E));
target->Set(v8::String::NewSymbol("K_KP_RIGHTBRACE"), v8::Integer::New(SDLK_KP_RIGHTBRACE));
target->Set(v8::String::NewSymbol("K_KP_B"), v8::Integer::New(SDLK_KP_B));
target->Set(v8::String::NewSymbol("K_PRIOR"), v8::Integer::New(SDLK_PRIOR));
target->Set(v8::String::NewSymbol("K_EQUALS"), v8::Integer::New(SDLK_EQUALS));
target->Set(v8::String::NewSymbol("PIXELFORMAT_YUY2"), v8::Integer::New(SDL_PIXELFORMAT_YUY2));
target->Set(v8::String::NewSymbol("GL_CONTEXT_PROFILE_MASK"), v8::Integer::New(SDL_GL_CONTEXT_PROFILE_MASK));
target->Set(v8::String::NewSymbol("KMOD_RESERVED"), v8::Integer::New(KMOD_RESERVED));
target->Set(v8::String::NewSymbol("K_AUDIOPLAY"), v8::Integer::New(SDLK_AUDIOPLAY));
target->Set(v8::String::NewSymbol("SCANCODE_SELECT"), v8::Integer::New(SDL_SCANCODE_SELECT));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_START"), v8::Integer::New(SDL_CONTROLLER_BUTTON_START));
target->Set(v8::String::NewSymbol("GL_CONTEXT_PROFILE_COMPATIBILITY"), v8::Integer::New(SDL_GL_CONTEXT_PROFILE_COMPATIBILITY));
target->Set(v8::String::NewSymbol("WINDOWEVENT_CLOSE"), v8::Integer::New(SDL_WINDOWEVENT_CLOSE));
target->Set(v8::String::NewSymbol("K_MUTE"), v8::Integer::New(SDLK_MUTE));
target->Set(v8::String::NewSymbol("GL_CONTEXT_EGL"), v8::Integer::New(SDL_GL_CONTEXT_EGL));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGB888"), v8::Integer::New(SDL_PIXELFORMAT_RGB888));
target->Set(v8::String::NewSymbol("KMOD_NUM"), v8::Integer::New(KMOD_NUM));
target->Set(v8::String::NewSymbol("MIX_MAXVOLUME"), v8::Integer::New(SDL_MIX_MAXVOLUME));
target->Set(v8::String::NewSymbol("SCANCODE_SPACE"), v8::Integer::New(SDL_SCANCODE_SPACE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_MEMADD"), v8::Integer::New(SDL_SCANCODE_KP_MEMADD));
target->Set(v8::String::NewSymbol("INIT_TIMER"), v8::Integer::New(SDL_INIT_TIMER));
target->Set(v8::String::NewSymbol("SCANCODE_DISPLAYSWITCH"), v8::Integer::New(SDL_SCANCODE_DISPLAYSWITCH));
target->Set(v8::String::NewSymbol("MESSAGEBOX_COLOR_BUTTON_BACKGROUND"), v8::Integer::New(SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND));
target->Set(v8::String::NewSymbol("FLIP_VERTICAL"), v8::Integer::New(SDL_FLIP_VERTICAL));
target->Set(v8::String::NewSymbol("WINDOWEVENT_FOCUS_LOST"), v8::Integer::New(SDL_WINDOWEVENT_FOCUS_LOST));
target->Set(v8::String::NewSymbol("SCANCODE_KP_00"), v8::Integer::New(SDL_SCANCODE_KP_00));
target->Set(v8::String::NewSymbol("MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT"), v8::Integer::New(SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT));
target->Set(v8::String::NewSymbol("PREALLOC"), v8::Integer::New(SDL_PREALLOC));
target->Set(v8::String::NewSymbol("MULTIGESTURE"), v8::Integer::New(SDL_MULTIGESTURE));
target->Set(v8::String::NewSymbol("CONTROLLER_BINDTYPE_AXIS"), v8::Integer::New(SDL_CONTROLLER_BINDTYPE_AXIS));
target->Set(v8::String::NewSymbol("K_ESCAPE"), v8::Integer::New(SDLK_ESCAPE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_ENTER"), v8::Integer::New(SDL_SCANCODE_KP_ENTER));
target->Set(v8::String::NewSymbol("K_RSHIFT"), v8::Integer::New(SDLK_RSHIFT));
target->Set(v8::String::NewSymbol("SCANCODE_KP_CLEARENTRY"), v8::Integer::New(SDL_SCANCODE_KP_CLEARENTRY));
target->Set(v8::String::NewSymbol("K_KP_PLUS"), v8::Integer::New(SDLK_KP_PLUS));
target->Set(v8::String::NewSymbol("K_PAGEDOWN"), v8::Integer::New(SDLK_PAGEDOWN));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_BACK"), v8::Integer::New(SDL_CONTROLLER_BUTTON_BACK));
target->Set(v8::String::NewSymbol("ALPHA_OPAQUE"), v8::Integer::New(SDL_ALPHA_OPAQUE));
target->Set(v8::String::NewSymbol("CONTROLLER_BINDTYPE_HAT"), v8::Integer::New(SDL_CONTROLLER_BINDTYPE_HAT));
target->Set(v8::String::NewSymbol("TEXTEDITING"), v8::Integer::New(SDL_TEXTEDITING));
target->Set(v8::String::NewSymbol("KMOD_RSHIFT"), v8::Integer::New(KMOD_RSHIFT));
target->Set(v8::String::NewSymbol("ARRAYORDER_BGRA"), v8::Integer::New(SDL_ARRAYORDER_BGRA));
target->Set(v8::String::NewSymbol("PIXELFORMAT_ABGR8888"), v8::Integer::New(SDL_PIXELFORMAT_ABGR8888));
target->Set(v8::String::NewSymbol("SCANCODE_TAB"), v8::Integer::New(SDL_SCANCODE_TAB));
target->Set(v8::String::NewSymbol("MOUSEBUTTONUP"), v8::Integer::New(SDL_MOUSEBUTTONUP));
target->Set(v8::String::NewSymbol("K_KP_DECIMAL"), v8::Integer::New(SDLK_KP_DECIMAL));
target->Set(v8::String::NewSymbol("K_RIGHT"), v8::Integer::New(SDLK_RIGHT));
target->Set(v8::String::NewSymbol("K_PERIOD"), v8::Integer::New(SDLK_PERIOD));
target->Set(v8::String::NewSymbol("PACKEDLAYOUT_1555"), v8::Integer::New(SDL_PACKEDLAYOUT_1555));
target->Set(v8::String::NewSymbol("WINDOW_HIDDEN"), v8::Integer::New(SDL_WINDOW_HIDDEN));
target->Set(v8::String::NewSymbol("K_KP_GREATER"), v8::Integer::New(SDLK_KP_GREATER));
target->Set(v8::String::NewSymbol("SCANCODE_CURRENCYUNIT"), v8::Integer::New(SDL_SCANCODE_CURRENCYUNIT));
target->Set(v8::String::NewSymbol("K_TAB"), v8::Integer::New(SDLK_TAB));
target->Set(v8::String::NewSymbol("K_PLUS"), v8::Integer::New(SDLK_PLUS));
target->Set(v8::String::NewSymbol("INIT_EVERYTHING"), v8::Integer::New(SDL_INIT_EVERYTHING));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_ASSERT"), v8::Integer::New(SDL_LOG_CATEGORY_ASSERT));
target->Set(v8::String::NewSymbol("K_KP_CLEAR"), v8::Integer::New(SDLK_KP_CLEAR));
target->Set(v8::String::NewSymbol("SCANCODE_RALT"), v8::Integer::New(SDL_SCANCODE_RALT));
target->Set(v8::String::NewSymbol("SCANCODE_VOLUMEDOWN"), v8::Integer::New(SDL_SCANCODE_VOLUMEDOWN));
target->Set(v8::String::NewSymbol("ICONV_EINVAL"), v8::Integer::New(SDL_ICONV_EINVAL));
target->Set(v8::String::NewSymbol("SCANCODE_MEDIASELECT"), v8::Integer::New(SDL_SCANCODE_MEDIASELECT));
target->Set(v8::String::NewSymbol("WINDOWEVENT_FOCUS_GAINED"), v8::Integer::New(SDL_WINDOWEVENT_FOCUS_GAINED));
target->Set(v8::String::NewSymbol("K_KP_LESS"), v8::Integer::New(SDLK_KP_LESS));
target->Set(v8::String::NewSymbol("TEXTUREACCESS_STREAMING"), v8::Integer::New(SDL_TEXTUREACCESS_STREAMING));
target->Set(v8::String::NewSymbol("K_DOWN"), v8::Integer::New(SDLK_DOWN));
target->Set(v8::String::NewSymbol("K_u"), v8::Integer::New(SDLK_u));
target->Set(v8::String::NewSymbol("K_t"), v8::Integer::New(SDLK_t));
target->Set(v8::String::NewSymbol("K_w"), v8::Integer::New(SDLK_w));
target->Set(v8::String::NewSymbol("SCANCODE_F11"), v8::Integer::New(SDL_SCANCODE_F11));
target->Set(v8::String::NewSymbol("K_q"), v8::Integer::New(SDLK_q));
target->Set(v8::String::NewSymbol("K_p"), v8::Integer::New(SDLK_p));
target->Set(v8::String::NewSymbol("K_s"), v8::Integer::New(SDLK_s));
target->Set(v8::String::NewSymbol("K_r"), v8::Integer::New(SDLK_r));
target->Set(v8::String::NewSymbol("K_BACKSPACE"), v8::Integer::New(SDLK_BACKSPACE));
target->Set(v8::String::NewSymbol("K_PERCENT"), v8::Integer::New(SDLK_PERCENT));
target->Set(v8::String::NewSymbol("K_x"), v8::Integer::New(SDLK_x));
target->Set(v8::String::NewSymbol("WINDOWEVENT_MOVED"), v8::Integer::New(SDL_WINDOWEVENT_MOVED));
target->Set(v8::String::NewSymbol("SCANCODE_CURRENCYSUBUNIT"), v8::Integer::New(SDL_SCANCODE_CURRENCYSUBUNIT));
target->Set(v8::String::NewSymbol("GL_MULTISAMPLESAMPLES"), v8::Integer::New(SDL_GL_MULTISAMPLESAMPLES));
target->Set(v8::String::NewSymbol("K_g"), v8::Integer::New(SDLK_g));
target->Set(v8::String::NewSymbol("K_f"), v8::Integer::New(SDLK_f));
target->Set(v8::String::NewSymbol("K_a"), v8::Integer::New(SDLK_a));
target->Set(v8::String::NewSymbol("K_c"), v8::Integer::New(SDLK_c));
target->Set(v8::String::NewSymbol("SCANCODE_KP_MEMMULTIPLY"), v8::Integer::New(SDL_SCANCODE_KP_MEMMULTIPLY));
target->Set(v8::String::NewSymbol("K_m"), v8::Integer::New(SDLK_m));
target->Set(v8::String::NewSymbol("K_l"), v8::Integer::New(SDLK_l));
target->Set(v8::String::NewSymbol("SCANCODE_RIGHTBRACKET"), v8::Integer::New(SDL_SCANCODE_RIGHTBRACKET));
target->Set(v8::String::NewSymbol("SCANCODE_PAUSE"), v8::Integer::New(SDL_SCANCODE_PAUSE));
target->Set(v8::String::NewSymbol("K_i"), v8::Integer::New(SDLK_i));
target->Set(v8::String::NewSymbol("K_h"), v8::Integer::New(SDLK_h));
target->Set(v8::String::NewSymbol("K_k"), v8::Integer::New(SDLK_k));
target->Set(v8::String::NewSymbol("K_j"), v8::Integer::New(SDLK_j));
target->Set(v8::String::NewSymbol("GL_BUFFER_SIZE"), v8::Integer::New(SDL_GL_BUFFER_SIZE));
target->Set(v8::String::NewSymbol("K_AC_BACK"), v8::Integer::New(SDLK_AC_BACK));
target->Set(v8::String::NewSymbol("SCANCODE_KP_BINARY"), v8::Integer::New(SDL_SCANCODE_KP_BINARY));
target->Set(v8::String::NewSymbol("CONTROLLER_AXIS_LEFTY"), v8::Integer::New(SDL_CONTROLLER_AXIS_LEFTY));
target->Set(v8::String::NewSymbol("CONTROLLER_AXIS_LEFTX"), v8::Integer::New(SDL_CONTROLLER_AXIS_LEFTX));
target->Set(v8::String::NewSymbol("WINDOW_SHOWN"), v8::Integer::New(SDL_WINDOW_SHOWN));
target->Set(v8::String::NewSymbol("K_LALT"), v8::Integer::New(SDLK_LALT));
target->Set(v8::String::NewSymbol("SCANCODE_KP_EXCLAM"), v8::Integer::New(SDL_SCANCODE_KP_EXCLAM));
target->Set(v8::String::NewSymbol("K_EXCLAIM"), v8::Integer::New(SDLK_EXCLAIM));
target->Set(v8::String::NewSymbol("SCANCODE_KP_MEMSUBTRACT"), v8::Integer::New(SDL_SCANCODE_KP_MEMSUBTRACT));
target->Set(v8::String::NewSymbol("K_5"), v8::Integer::New(SDLK_5));
target->Set(v8::String::NewSymbol("K_4"), v8::Integer::New(SDLK_4));
target->Set(v8::String::NewSymbol("SCANCODE_AC_SEARCH"), v8::Integer::New(SDL_SCANCODE_AC_SEARCH));
target->Set(v8::String::NewSymbol("K_6"), v8::Integer::New(SDLK_6));
target->Set(v8::String::NewSymbol("K_1"), v8::Integer::New(SDLK_1));
target->Set(v8::String::NewSymbol("K_0"), v8::Integer::New(SDLK_0));
target->Set(v8::String::NewSymbol("PACKEDLAYOUT_5551"), v8::Integer::New(SDL_PACKEDLAYOUT_5551));
target->Set(v8::String::NewSymbol("K_2"), v8::Integer::New(SDLK_2));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_VIDEO"), v8::Integer::New(SDL_LOG_CATEGORY_VIDEO));
target->Set(v8::String::NewSymbol("K_RIGHTPAREN"), v8::Integer::New(SDLK_RIGHTPAREN));
target->Set(v8::String::NewSymbol("K_8"), v8::Integer::New(SDLK_8));
target->Set(v8::String::NewSymbol("GL_DEPTH_SIZE"), v8::Integer::New(SDL_GL_DEPTH_SIZE));
target->Set(v8::String::NewSymbol("KMOD_MODE"), v8::Integer::New(KMOD_MODE));
target->Set(v8::String::NewSymbol("K_KP_COLON"), v8::Integer::New(SDLK_KP_COLON));
target->Set(v8::String::NewSymbol("FINGERUP"), v8::Integer::New(SDL_FINGERUP));
target->Set(v8::String::NewSymbol("K_LEFTBRACKET"), v8::Integer::New(SDLK_LEFTBRACKET));
target->Set(v8::String::NewSymbol("ICONV_ERROR"), v8::Integer::New(SDL_ICONV_ERROR));
target->Set(v8::String::NewSymbol("SCANCODE_KP_XOR"), v8::Integer::New(SDL_SCANCODE_KP_XOR));
target->Set(v8::String::NewSymbol("GL_ACCUM_BLUE_SIZE"), v8::Integer::New(SDL_GL_ACCUM_BLUE_SIZE));
target->Set(v8::String::NewSymbol("K_SPACE"), v8::Integer::New(SDLK_SPACE));
target->Set(v8::String::NewSymbol("SCANCODE_HOME"), v8::Integer::New(SDL_SCANCODE_HOME));
target->Set(v8::String::NewSymbol("K_SEPARATOR"), v8::Integer::New(SDLK_SEPARATOR));
target->Set(v8::String::NewSymbol("JOYDEVICEADDED"), v8::Integer::New(SDL_JOYDEVICEADDED));
target->Set(v8::String::NewSymbol("AUDIO_STOPPED"), v8::Integer::New(SDL_AUDIO_STOPPED));
target->Set(v8::String::NewSymbol("K_CANCEL"), v8::Integer::New(SDLK_CANCEL));
target->Set(v8::String::NewSymbol("INPUTPROXIMITYOUT"), v8::Integer::New(SDL_INPUTPROXIMITYOUT));
target->Set(v8::String::NewSymbol("PIXELTYPE_ARRAYU16"), v8::Integer::New(SDL_PIXELTYPE_ARRAYU16));
target->Set(v8::String::NewSymbol("K_COMPUTER"), v8::Integer::New(SDLK_COMPUTER));
target->Set(v8::String::NewSymbol("KMOD_RALT"), v8::Integer::New(KMOD_RALT));
target->Set(v8::String::NewSymbol("PIXELFORMAT_YVYU"), v8::Integer::New(SDL_PIXELFORMAT_YVYU));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_SIZEWE"), v8::Integer::New(SDL_SYSTEM_CURSOR_SIZEWE));
target->Set(v8::String::NewSymbol("GL_DOUBLEBUFFER"), v8::Integer::New(SDL_GL_DOUBLEBUFFER));
target->Set(v8::String::NewSymbol("SCANCODE_KP_MULTIPLY"), v8::Integer::New(SDL_SCANCODE_KP_MULTIPLY));
target->Set(v8::String::NewSymbol("PIXELFORMAT_BGR555"), v8::Integer::New(SDL_PIXELFORMAT_BGR555));
target->Set(v8::String::NewSymbol("K_AC_BOOKMARKS"), v8::Integer::New(SDLK_AC_BOOKMARKS));
target->Set(v8::String::NewSymbol("PIXELFORMAT_INDEX8"), v8::Integer::New(SDL_PIXELFORMAT_INDEX8));
target->Set(v8::String::NewSymbol("KMOD_LCTRL"), v8::Integer::New(KMOD_LCTRL));
target->Set(v8::String::NewSymbol("FIRSTEVENT"), v8::Integer::New(SDL_FIRSTEVENT));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_APPLICATION"), v8::Integer::New(SDL_LOG_CATEGORY_APPLICATION));
target->Set(v8::String::NewSymbol("PIXELTYPE_PACKED16"), v8::Integer::New(SDL_PIXELTYPE_PACKED16));
target->Set(v8::String::NewSymbol("PACKEDORDER_ARGB"), v8::Integer::New(SDL_PACKEDORDER_ARGB));
target->Set(v8::String::NewSymbol("K_RETURN2"), v8::Integer::New(SDLK_RETURN2));
target->Set(v8::String::NewSymbol("SCANCODE_KP_MEMDIVIDE"), v8::Integer::New(SDL_SCANCODE_KP_MEMDIVIDE));
target->Set(v8::String::NewSymbol("PIXELTYPE_PACKED8"), v8::Integer::New(SDL_PIXELTYPE_PACKED8));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_DPAD_UP"), v8::Integer::New(SDL_CONTROLLER_BUTTON_DPAD_UP));
target->Set(v8::String::NewSymbol("BUTTON_X2MASK"), v8::Integer::New(SDL_BUTTON_X2MASK));
target->Set(v8::String::NewSymbol("K_BRIGHTNESSDOWN"), v8::Integer::New(SDLK_BRIGHTNESSDOWN));
target->Set(v8::String::NewSymbol("GL_BLUE_SIZE"), v8::Integer::New(SDL_GL_BLUE_SIZE));
target->Set(v8::String::NewSymbol("K_KP_COMMA"), v8::Integer::New(SDLK_KP_COMMA));
target->Set(v8::String::NewSymbol("HINT_NORMAL"), v8::Integer::New(SDL_HINT_NORMAL));
target->Set(v8::String::NewSymbol("K_CLEAR"), v8::Integer::New(SDLK_CLEAR));
target->Set(v8::String::NewSymbol("WINDOWEVENT_HIDDEN"), v8::Integer::New(SDL_WINDOWEVENT_HIDDEN));
target->Set(v8::String::NewSymbol("K_KP_MEMSUBTRACT"), v8::Integer::New(SDLK_KP_MEMSUBTRACT));
target->Set(v8::String::NewSymbol("GL_CONTEXT_ROBUST_ACCESS_FLAG"), v8::Integer::New(SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG));
target->Set(v8::String::NewSymbol("SCANCODE_AC_BACK"), v8::Integer::New(SDL_SCANCODE_AC_BACK));
target->Set(v8::String::NewSymbol("LINE"), v8::Integer::New(SDL_LINE));
target->Set(v8::String::NewSymbol("K_KP_9"), v8::Integer::New(SDLK_KP_9));
target->Set(v8::String::NewSymbol("SCANCODE_KP_CLEAR"), v8::Integer::New(SDL_SCANCODE_KP_CLEAR));
target->Set(v8::String::NewSymbol("SCANCODE_BRIGHTNESSUP"), v8::Integer::New(SDL_SCANCODE_BRIGHTNESSUP));
target->Set(v8::String::NewSymbol("SCANCODE_AC_HOME"), v8::Integer::New(SDL_SCANCODE_AC_HOME));
target->Set(v8::String::NewSymbol("HAT_UP"), v8::Integer::New(SDL_HAT_UP));
target->Set(v8::String::NewSymbol("CONTROLLERDEVICEREMOVED"), v8::Integer::New(SDL_CONTROLLERDEVICEREMOVED));
target->Set(v8::String::NewSymbol("SCANCODE_UP"), v8::Integer::New(SDL_SCANCODE_UP));
target->Set(v8::String::NewSymbol("PIXELFORMAT_UYVY"), v8::Integer::New(SDL_PIXELFORMAT_UYVY));
target->Set(v8::String::NewSymbol("K_DISPLAYSWITCH"), v8::Integer::New(SDLK_DISPLAYSWITCH));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_NO"), v8::Integer::New(SDL_SYSTEM_CURSOR_NO));
target->Set(v8::String::NewSymbol("PACKEDLAYOUT_8888"), v8::Integer::New(SDL_PACKEDLAYOUT_8888));
target->Set(v8::String::NewSymbol("K_CURRENCYUNIT"), v8::Integer::New(SDLK_CURRENCYUNIT));
target->Set(v8::String::NewSymbol("SCANCODE_MUTE"), v8::Integer::New(SDL_SCANCODE_MUTE));
target->Set(v8::String::NewSymbol("K_END"), v8::Integer::New(SDLK_END));
target->Set(v8::String::NewSymbol("PIXELFORMAT_ARGB2101010"), v8::Integer::New(SDL_PIXELFORMAT_ARGB2101010));
target->Set(v8::String::NewSymbol("BITMAPORDER_4321"), v8::Integer::New(SDL_BITMAPORDER_4321));
target->Set(v8::String::NewSymbol("PIXELFORMAT_ARGB8888"), v8::Integer::New(SDL_PIXELFORMAT_ARGB8888));
target->Set(v8::String::NewSymbol("PIXELFORMAT_BGRA5551"), v8::Integer::New(SDL_PIXELFORMAT_BGRA5551));
target->Set(v8::String::NewSymbol("HINT_DEFAULT"), v8::Integer::New(SDL_HINT_DEFAULT));
target->Set(v8::String::NewSymbol("K_RGUI"), v8::Integer::New(SDLK_RGUI));
target->Set(v8::String::NewSymbol("GL_ACCUM_GREEN_SIZE"), v8::Integer::New(SDL_GL_ACCUM_GREEN_SIZE));
target->Set(v8::String::NewSymbol("K_LGUI"), v8::Integer::New(SDLK_LGUI));
target->Set(v8::String::NewSymbol("SCANCODE_F18"), v8::Integer::New(SDL_SCANCODE_F18));
target->Set(v8::String::NewSymbol("SCANCODE_F19"), v8::Integer::New(SDL_SCANCODE_F19));
target->Set(v8::String::NewSymbol("K_DOLLAR"), v8::Integer::New(SDLK_DOLLAR));
target->Set(v8::String::NewSymbol("SCANCODE_KP_TAB"), v8::Integer::New(SDL_SCANCODE_KP_TAB));
target->Set(v8::String::NewSymbol("SCANCODE_F12"), v8::Integer::New(SDL_SCANCODE_F12));
target->Set(v8::String::NewSymbol("SCANCODE_F13"), v8::Integer::New(SDL_SCANCODE_F13));
target->Set(v8::String::NewSymbol("SCANCODE_F10"), v8::Integer::New(SDL_SCANCODE_F10));
target->Set(v8::String::NewSymbol("PRESSED"), v8::Integer::New(SDL_PRESSED));
target->Set(v8::String::NewSymbol("SCANCODE_F16"), v8::Integer::New(SDL_SCANCODE_F16));
target->Set(v8::String::NewSymbol("SCANCODE_F17"), v8::Integer::New(SDL_SCANCODE_F17));
target->Set(v8::String::NewSymbol("SCANCODE_F14"), v8::Integer::New(SDL_SCANCODE_F14));
target->Set(v8::String::NewSymbol("SCANCODE_F15"), v8::Integer::New(SDL_SCANCODE_F15));
target->Set(v8::String::NewSymbol("PACKEDORDER_XBGR"), v8::Integer::New(SDL_PACKEDORDER_XBGR));
target->Set(v8::String::NewSymbol("K_d"), v8::Integer::New(SDLK_d));
target->Set(v8::String::NewSymbol("SCANCODE_DECIMALSEPARATOR"), v8::Integer::New(SDL_SCANCODE_DECIMALSEPARATOR));
target->Set(v8::String::NewSymbol("AUDIO_MASK_BITSIZE"), v8::Integer::New(SDL_AUDIO_MASK_BITSIZE));
target->Set(v8::String::NewSymbol("ENABLE"), v8::Integer::New(SDL_ENABLE));
target->Set(v8::String::NewSymbol("POWERSTATE_UNKNOWN"), v8::Integer::New(SDL_POWERSTATE_UNKNOWN));
target->Set(v8::String::NewSymbol("RENDERER_PRESENTVSYNC"), v8::Integer::New(SDL_RENDERER_PRESENTVSYNC));
target->Set(v8::String::NewSymbol("K_UNDO"), v8::Integer::New(SDLK_UNDO));
target->Set(v8::String::NewSymbol("SCANCODE_D"), v8::Integer::New(SDL_SCANCODE_D));
target->Set(v8::String::NewSymbol("K_AUDIOPREV"), v8::Integer::New(SDLK_AUDIOPREV));
target->Set(v8::String::NewSymbol("GL_CONTEXT_MINOR_VERSION"), v8::Integer::New(SDL_GL_CONTEXT_MINOR_VERSION));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_HAND"), v8::Integer::New(SDL_SYSTEM_CURSOR_HAND));
target->Set(v8::String::NewSymbol("PEEKEVENT"), v8::Integer::New(SDL_PEEKEVENT));
target->Set(v8::String::NewSymbol("AUDIO_PAUSED"), v8::Integer::New(SDL_AUDIO_PAUSED));
target->Set(v8::String::NewSymbol("TEXTUREMODULATE_COLOR"), v8::Integer::New(SDL_TEXTUREMODULATE_COLOR));
target->Set(v8::String::NewSymbol("K_PRINTSCREEN"), v8::Integer::New(SDLK_PRINTSCREEN));
target->Set(v8::String::NewSymbol("MESSAGEBOX_COLOR_BUTTON_SELECTED"), v8::Integer::New(SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED));
target->Set(v8::String::NewSymbol("K_SYSREQ"), v8::Integer::New(SDLK_SYSREQ));
target->Set(v8::String::NewSymbol("K_F12"), v8::Integer::New(SDLK_F12));
target->Set(v8::String::NewSymbol("K_F13"), v8::Integer::New(SDLK_F13));
target->Set(v8::String::NewSymbol("K_F10"), v8::Integer::New(SDLK_F10));
target->Set(v8::String::NewSymbol("SCANCODE_KP_RIGHTPAREN"), v8::Integer::New(SDL_SCANCODE_KP_RIGHTPAREN));
target->Set(v8::String::NewSymbol("WINDOWPOS_UNDEFINED_MASK"), v8::Integer::New(SDL_WINDOWPOS_UNDEFINED_MASK));
target->Set(v8::String::NewSymbol("SCANCODE_UNKNOWN"), v8::Integer::New(SDL_SCANCODE_UNKNOWN));
target->Set(v8::String::NewSymbol("K_F14"), v8::Integer::New(SDLK_F14));
target->Set(v8::String::NewSymbol("K_F15"), v8::Integer::New(SDLK_F15));
target->Set(v8::String::NewSymbol("SWSURFACE"), v8::Integer::New(SDL_SWSURFACE));
target->Set(v8::String::NewSymbol("SCANCODE_LGUI"), v8::Integer::New(SDL_SCANCODE_LGUI));
target->Set(v8::String::NewSymbol("K_F18"), v8::Integer::New(SDLK_F18));
target->Set(v8::String::NewSymbol("K_F19"), v8::Integer::New(SDLK_F19));
target->Set(v8::String::NewSymbol("K_UNKNOWN"), v8::Integer::New(SDLK_UNKNOWN));
target->Set(v8::String::NewSymbol("SCANCODE_LANG9"), v8::Integer::New(SDL_SCANCODE_LANG9));
target->Set(v8::String::NewSymbol("SCANCODE_LANG8"), v8::Integer::New(SDL_SCANCODE_LANG8));
target->Set(v8::String::NewSymbol("RENDERER_ACCELERATED"), v8::Integer::New(SDL_RENDERER_ACCELERATED));
target->Set(v8::String::NewSymbol("SCANCODE_CANCEL"), v8::Integer::New(SDL_SCANCODE_CANCEL));
target->Set(v8::String::NewSymbol("SCANCODE_BRIGHTNESSDOWN"), v8::Integer::New(SDL_SCANCODE_BRIGHTNESSDOWN));
target->Set(v8::String::NewSymbol("SCANCODE_LANG1"), v8::Integer::New(SDL_SCANCODE_LANG1));
target->Set(v8::String::NewSymbol("SCANCODE_LANG3"), v8::Integer::New(SDL_SCANCODE_LANG3));
target->Set(v8::String::NewSymbol("SCANCODE_LANG2"), v8::Integer::New(SDL_SCANCODE_LANG2));
target->Set(v8::String::NewSymbol("SCANCODE_LANG5"), v8::Integer::New(SDL_SCANCODE_LANG5));
target->Set(v8::String::NewSymbol("WINDOW_OPENGL"), v8::Integer::New(SDL_WINDOW_OPENGL));
target->Set(v8::String::NewSymbol("SCANCODE_LANG7"), v8::Integer::New(SDL_SCANCODE_LANG7));
target->Set(v8::String::NewSymbol("SCANCODE_LANG6"), v8::Integer::New(SDL_SCANCODE_LANG6));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_WAIT"), v8::Integer::New(SDL_SYSTEM_CURSOR_WAIT));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED5"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED5));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED6"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED6));
target->Set(v8::String::NewSymbol("K_F11"), v8::Integer::New(SDLK_F11));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RENDER"), v8::Integer::New(SDL_LOG_CATEGORY_RENDER));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED2"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED2));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED3"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED3));
target->Set(v8::String::NewSymbol("SCANCODE_EXSEL"), v8::Integer::New(SDL_SCANCODE_EXSEL));
target->Set(v8::String::NewSymbol("K_F16"), v8::Integer::New(SDLK_F16));
target->Set(v8::String::NewSymbol("SCANCODE_SEMICOLON"), v8::Integer::New(SDL_SCANCODE_SEMICOLON));
target->Set(v8::String::NewSymbol("NUM_SYSTEM_CURSORS"), v8::Integer::New(SDL_NUM_SYSTEM_CURSORS));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED9"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED9));
target->Set(v8::String::NewSymbol("K_F17"), v8::Integer::New(SDLK_F17));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_DPAD_RIGHT"), v8::Integer::New(SDL_CONTROLLER_BUTTON_DPAD_RIGHT));
target->Set(v8::String::NewSymbol("K_RALT"), v8::Integer::New(SDLK_RALT));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_SIZENESW"), v8::Integer::New(SDL_SYSTEM_CURSOR_SIZENESW));
target->Set(v8::String::NewSymbol("SCANCODE_APPLICATION"), v8::Integer::New(SDL_SCANCODE_APPLICATION));
target->Set(v8::String::NewSymbol("NUM_LOG_PRIORITIES"), v8::Integer::New(SDL_NUM_LOG_PRIORITIES));
target->Set(v8::String::NewSymbol("K_KP_PERCENT"), v8::Integer::New(SDLK_KP_PERCENT));
target->Set(v8::String::NewSymbol("K_PAUSE"), v8::Integer::New(SDLK_PAUSE));
target->Set(v8::String::NewSymbol("K_BACKSLASH"), v8::Integer::New(SDLK_BACKSLASH));
target->Set(v8::String::NewSymbol("K_SCROLLLOCK"), v8::Integer::New(SDLK_SCROLLLOCK));
target->Set(v8::String::NewSymbol("K_KP_TAB"), v8::Integer::New(SDLK_KP_TAB));
target->Set(v8::String::NewSymbol("SCANCODE_CRSEL"), v8::Integer::New(SDL_SCANCODE_CRSEL));
target->Set(v8::String::NewSymbol("WINDOW_MOUSE_FOCUS"), v8::Integer::New(SDL_WINDOW_MOUSE_FOCUS));
target->Set(v8::String::NewSymbol("K_KP_DBLVERTICALBAR"), v8::Integer::New(SDLK_KP_DBLVERTICALBAR));
target->Set(v8::String::NewSymbol("SCANCODE_V"), v8::Integer::New(SDL_SCANCODE_V));
target->Set(v8::String::NewSymbol("MAJOR_VERSION"), v8::Integer::New(SDL_MAJOR_VERSION));
target->Set(v8::String::NewSymbol("CONTROLLER_AXIS_RIGHTX"), v8::Integer::New(SDL_CONTROLLER_AXIS_RIGHTX));
target->Set(v8::String::NewSymbol("SCANCODE_Q"), v8::Integer::New(SDL_SCANCODE_Q));
target->Set(v8::String::NewSymbol("TEXTUREMODULATE_NONE"), v8::Integer::New(SDL_TEXTUREMODULATE_NONE));
target->Set(v8::String::NewSymbol("KMOD_CAPS"), v8::Integer::New(KMOD_CAPS));
target->Set(v8::String::NewSymbol("K_MAIL"), v8::Integer::New(SDLK_MAIL));
target->Set(v8::String::NewSymbol("SCANCODE_P"), v8::Integer::New(SDL_SCANCODE_P));
target->Set(v8::String::NewSymbol("MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT"), v8::Integer::New(SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT));
target->Set(v8::String::NewSymbol("BLENDMODE_NONE"), v8::Integer::New(SDL_BLENDMODE_NONE));
target->Set(v8::String::NewSymbol("TOUCHBUTTONDOWN"), v8::Integer::New(SDL_TOUCHBUTTONDOWN));
target->Set(v8::String::NewSymbol("K_FIND"), v8::Integer::New(SDLK_FIND));
target->Set(v8::String::NewSymbol("K_KP_MINUS"), v8::Integer::New(SDLK_KP_MINUS));
target->Set(v8::String::NewSymbol("WINDOWEVENT_MINIMIZED"), v8::Integer::New(SDL_WINDOWEVENT_MINIMIZED));
target->Set(v8::String::NewSymbol("HAT_LEFT"), v8::Integer::New(SDL_HAT_LEFT));
target->Set(v8::String::NewSymbol("PIXELFORMAT_BGRA4444"), v8::Integer::New(SDL_PIXELFORMAT_BGRA4444));
target->Set(v8::String::NewSymbol("K_KP_1"), v8::Integer::New(SDLK_KP_1));
target->Set(v8::String::NewSymbol("KMOD_RGUI"), v8::Integer::New(KMOD_RGUI));
target->Set(v8::String::NewSymbol("CONTROLLER_AXIS_TRIGGERLEFT"), v8::Integer::New(SDL_CONTROLLER_AXIS_TRIGGERLEFT));
target->Set(v8::String::NewSymbol("SCANCODE_INSERT"), v8::Integer::New(SDL_SCANCODE_INSERT));
target->Set(v8::String::NewSymbol("SCANCODE_LCTRL"), v8::Integer::New(SDL_SCANCODE_LCTRL));
target->Set(v8::String::NewSymbol("K_PAGEUP"), v8::Integer::New(SDLK_PAGEUP));
target->Set(v8::String::NewSymbol("SCANCODE_VOLUMEUP"), v8::Integer::New(SDL_SCANCODE_VOLUMEUP));
target->Set(v8::String::NewSymbol("K_COLON"), v8::Integer::New(SDLK_COLON));
target->Set(v8::String::NewSymbol("SCANCODE_BACKSLASH"), v8::Integer::New(SDL_SCANCODE_BACKSLASH));
target->Set(v8::String::NewSymbol("PIXELFORMAT_ARGB1555"), v8::Integer::New(SDL_PIXELFORMAT_ARGB1555));
target->Set(v8::String::NewSymbol("DONTFREE"), v8::Integer::New(SDL_DONTFREE));
target->Set(v8::String::NewSymbol("SCANCODE_CLEARAGAIN"), v8::Integer::New(SDL_SCANCODE_CLEARAGAIN));
target->Set(v8::String::NewSymbol("SCANCODE_AUDIOMUTE"), v8::Integer::New(SDL_SCANCODE_AUDIOMUTE));
target->Set(v8::String::NewSymbol("K_KP_2"), v8::Integer::New(SDLK_KP_2));
target->Set(v8::String::NewSymbol("SCANCODE_KP_HEXADECIMAL"), v8::Integer::New(SDL_SCANCODE_KP_HEXADECIMAL));
target->Set(v8::String::NewSymbol("SCANCODE_KP_DIVIDE"), v8::Integer::New(SDL_SCANCODE_KP_DIVIDE));
target->Set(v8::String::NewSymbol("K_APPLICATION"), v8::Integer::New(SDLK_APPLICATION));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_GUIDE"), v8::Integer::New(SDL_CONTROLLER_BUTTON_GUIDE));
target->Set(v8::String::NewSymbol("PIXELTYPE_ARRAYF16"), v8::Integer::New(SDL_PIXELTYPE_ARRAYF16));
target->Set(v8::String::NewSymbol("PACKEDLAYOUT_4444"), v8::Integer::New(SDL_PACKEDLAYOUT_4444));
target->Set(v8::String::NewSymbol("SCANCODE_RSHIFT"), v8::Integer::New(SDL_SCANCODE_RSHIFT));
target->Set(v8::String::NewSymbol("PIXELFORMAT_BGRX8888"), v8::Integer::New(SDL_PIXELFORMAT_BGRX8888));
target->Set(v8::String::NewSymbol("K_SELECT"), v8::Integer::New(SDLK_SELECT));
target->Set(v8::String::NewSymbol("THREAD_PRIORITY_NORMAL"), v8::Integer::New(SDL_THREAD_PRIORITY_NORMAL));
target->Set(v8::String::NewSymbol("PACKEDORDER_XRGB"), v8::Integer::New(SDL_PACKEDORDER_XRGB));
target->Set(v8::String::NewSymbol("WINDOWPOS_UNDEFINED"), v8::Integer::New(SDL_WINDOWPOS_UNDEFINED));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_CROSSHAIR"), v8::Integer::New(SDL_SYSTEM_CURSOR_CROSSHAIR));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_LEFTSTICK"), v8::Integer::New(SDL_CONTROLLER_BUTTON_LEFTSTICK));
target->Set(v8::String::NewSymbol("LIL_ENDIAN"), v8::Integer::New(SDL_LIL_ENDIAN));
target->Set(v8::String::NewSymbol("CACHELINE_SIZE"), v8::Integer::New(SDL_CACHELINE_SIZE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_LESS"), v8::Integer::New(SDL_SCANCODE_KP_LESS));
target->Set(v8::String::NewSymbol("SCANCODE_LANG4"), v8::Integer::New(SDL_SCANCODE_LANG4));
target->Set(v8::String::NewSymbol("DOLLARGESTURE"), v8::Integer::New(SDL_DOLLARGESTURE));
target->Set(v8::String::NewSymbol("CONTROLLERDEVICEADDED"), v8::Integer::New(SDL_CONTROLLERDEVICEADDED));
target->Set(v8::String::NewSymbol("SCANCODE_DOWN"), v8::Integer::New(SDL_SCANCODE_DOWN));
target->Set(v8::String::NewSymbol("K_LCTRL"), v8::Integer::New(SDLK_LCTRL));
target->Set(v8::String::NewSymbol("TEXTEDITINGEVENT_TEXT_SIZE"), v8::Integer::New(SDL_TEXTEDITINGEVENT_TEXT_SIZE));
target->Set(v8::String::NewSymbol("K_LEFTPAREN"), v8::Integer::New(SDLK_LEFTPAREN));
target->Set(v8::String::NewSymbol("SYSTEM_CURSOR_IBEAM"), v8::Integer::New(SDL_SYSTEM_CURSOR_IBEAM));
target->Set(v8::String::NewSymbol("BUTTON_MMASK"), v8::Integer::New(SDL_BUTTON_MMASK));
target->Set(v8::String::NewSymbol("PIXELTYPE_ARRAYF32"), v8::Integer::New(SDL_PIXELTYPE_ARRAYF32));
target->Set(v8::String::NewSymbol("BUTTON_X1MASK"), v8::Integer::New(SDL_BUTTON_X1MASK));
target->Set(v8::String::NewSymbol("USEREVENT"), v8::Integer::New(SDL_USEREVENT));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED4"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED4));
target->Set(v8::String::NewSymbol("CONTROLLERBUTTONUP"), v8::Integer::New(SDL_CONTROLLERBUTTONUP));
target->Set(v8::String::NewSymbol("FLIP_NONE"), v8::Integer::New(SDL_FLIP_NONE));
target->Set(v8::String::NewSymbol("THREAD_PRIORITY_HIGH"), v8::Integer::New(SDL_THREAD_PRIORITY_HIGH));
target->Set(v8::String::NewSymbol("LOG_PRIORITY_DEBUG"), v8::Integer::New(SDL_LOG_PRIORITY_DEBUG));
target->Set(v8::String::NewSymbol("PIXELFORMAT_ARGB4444"), v8::Integer::New(SDL_PIXELFORMAT_ARGB4444));
target->Set(v8::String::NewSymbol("K_KP_C"), v8::Integer::New(SDLK_KP_C));
target->Set(v8::String::NewSymbol("SCANCODE_SCROLLLOCK"), v8::Integer::New(SDL_SCANCODE_SCROLLLOCK));
target->Set(v8::String::NewSymbol("SCANCODE_F1"), v8::Integer::New(SDL_SCANCODE_F1));
target->Set(v8::String::NewSymbol("SCANCODE_F2"), v8::Integer::New(SDL_SCANCODE_F2));
target->Set(v8::String::NewSymbol("GL_STEREO"), v8::Integer::New(SDL_GL_STEREO));
target->Set(v8::String::NewSymbol("SCANCODE_F4"), v8::Integer::New(SDL_SCANCODE_F4));
target->Set(v8::String::NewSymbol("BLENDMODE_BLEND"), v8::Integer::New(SDL_BLENDMODE_BLEND));
target->Set(v8::String::NewSymbol("SCANCODE_F6"), v8::Integer::New(SDL_SCANCODE_F6));
target->Set(v8::String::NewSymbol("SCANCODE_F7"), v8::Integer::New(SDL_SCANCODE_F7));
target->Set(v8::String::NewSymbol("SCANCODE_F8"), v8::Integer::New(SDL_SCANCODE_F8));
target->Set(v8::String::NewSymbol("SCANCODE_F9"), v8::Integer::New(SDL_SCANCODE_F9));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED1"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED1));
target->Set(v8::String::NewSymbol("K_OPER"), v8::Integer::New(SDLK_OPER));
target->Set(v8::String::NewSymbol("INPUTBUTTONDOWN"), v8::Integer::New(SDL_INPUTBUTTONDOWN));
target->Set(v8::String::NewSymbol("RELEASED"), v8::Integer::New(SDL_RELEASED));
target->Set(v8::String::NewSymbol("TEXTUREMODULATE_ALPHA"), v8::Integer::New(SDL_TEXTUREMODULATE_ALPHA));
target->Set(v8::String::NewSymbol("MUTEX_TIMEDOUT"), v8::Integer::New(SDL_MUTEX_TIMEDOUT));
target->Set(v8::String::NewSymbol("KMOD_LSHIFT"), v8::Integer::New(KMOD_LSHIFT));
target->Set(v8::String::NewSymbol("K_KP_EQUALS"), v8::Integer::New(SDLK_KP_EQUALS));
target->Set(v8::String::NewSymbol("HAT_LEFTUP"), v8::Integer::New(SDL_HAT_LEFTUP));
target->Set(v8::String::NewSymbol("K_AUDIOSTOP"), v8::Integer::New(SDLK_AUDIOSTOP));
target->Set(v8::String::NewSymbol("K_v"), v8::Integer::New(SDLK_v));
target->Set(v8::String::NewSymbol("ALPHA_TRANSPARENT"), v8::Integer::New(SDL_ALPHA_TRANSPARENT));
target->Set(v8::String::NewSymbol("K_BACKQUOTE"), v8::Integer::New(SDLK_BACKQUOTE));
target->Set(v8::String::NewSymbol("WINDOWEVENT_SIZE_CHANGED"), v8::Integer::New(SDL_WINDOWEVENT_SIZE_CHANGED));
target->Set(v8::String::NewSymbol("PIXELTYPE_ARRAYU8"), v8::Integer::New(SDL_PIXELTYPE_ARRAYU8));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED8"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED8));
target->Set(v8::String::NewSymbol("SCANCODE_AUDIONEXT"), v8::Integer::New(SDL_SCANCODE_AUDIONEXT));
target->Set(v8::String::NewSymbol("MESSAGEBOX_ERROR"), v8::Integer::New(SDL_MESSAGEBOX_ERROR));
target->Set(v8::String::NewSymbol("ASSERTION_RETRY"), v8::Integer::New(SDL_ASSERTION_RETRY));
target->Set(v8::String::NewSymbol("WINDOWEVENT_RESTORED"), v8::Integer::New(SDL_WINDOWEVENT_RESTORED));
target->Set(v8::String::NewSymbol("MOUSEBUTTONDOWN"), v8::Integer::New(SDL_MOUSEBUTTONDOWN));
target->Set(v8::String::NewSymbol("SCANCODE_MODE"), v8::Integer::New(SDL_SCANCODE_MODE));
target->Set(v8::String::NewSymbol("INPUTBUTTONUP"), v8::Integer::New(SDL_INPUTBUTTONUP));
target->Set(v8::String::NewSymbol("SCANCODE_F21"), v8::Integer::New(SDL_SCANCODE_F21));
target->Set(v8::String::NewSymbol("SCANCODE_WWW"), v8::Integer::New(SDL_SCANCODE_WWW));
target->Set(v8::String::NewSymbol("PIXELFORMAT_INDEX4LSB"), v8::Integer::New(SDL_PIXELFORMAT_INDEX4LSB));
target->Set(v8::String::NewSymbol("K_y"), v8::Integer::New(SDLK_y));
target->Set(v8::String::NewSymbol("K_AC_HOME"), v8::Integer::New(SDLK_AC_HOME));
target->Set(v8::String::NewSymbol("K_COPY"), v8::Integer::New(SDLK_COPY));
target->Set(v8::String::NewSymbol("K_CAPSLOCK"), v8::Integer::New(SDLK_CAPSLOCK));
target->Set(v8::String::NewSymbol("SCANCODE_KP_MINUS"), v8::Integer::New(SDL_SCANCODE_KP_MINUS));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_LEFTSHOULDER"), v8::Integer::New(SDL_CONTROLLER_BUTTON_LEFTSHOULDER));
target->Set(v8::String::NewSymbol("SCANCODE_KBDILLUMTOGGLE"), v8::Integer::New(SDL_SCANCODE_KBDILLUMTOGGLE));
target->Set(v8::String::NewSymbol("LOG_PRIORITY_INFO"), v8::Integer::New(SDL_LOG_PRIORITY_INFO));
target->Set(v8::String::NewSymbol("SCANCODE_EQUALS"), v8::Integer::New(SDL_SCANCODE_EQUALS));
target->Set(v8::String::NewSymbol("K_HELP"), v8::Integer::New(SDLK_HELP));
target->Set(v8::String::NewSymbol("K_z"), v8::Integer::New(SDLK_z));
target->Set(v8::String::NewSymbol("GL_CONTEXT_MAJOR_VERSION"), v8::Integer::New(SDL_GL_CONTEXT_MAJOR_VERSION));
target->Set(v8::String::NewSymbol("K_DECIMALSEPARATOR"), v8::Integer::New(SDLK_DECIMALSEPARATOR));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGB555"), v8::Integer::New(SDL_PIXELFORMAT_RGB555));
target->Set(v8::String::NewSymbol("TEXTINPUTEVENT_TEXT_SIZE"), v8::Integer::New(SDL_TEXTINPUTEVENT_TEXT_SIZE));
target->Set(v8::String::NewSymbol("THREAD_PRIORITY_LOW"), v8::Integer::New(SDL_THREAD_PRIORITY_LOW));
target->Set(v8::String::NewSymbol("HAT_RIGHTDOWN"), v8::Integer::New(SDL_HAT_RIGHTDOWN));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_Y"), v8::Integer::New(SDL_CONTROLLER_BUTTON_Y));
target->Set(v8::String::NewSymbol("SCANCODE_EXECUTE"), v8::Integer::New(SDL_SCANCODE_EXECUTE));
target->Set(v8::String::NewSymbol("HAT_LEFTDOWN"), v8::Integer::New(SDL_HAT_LEFTDOWN));
target->Set(v8::String::NewSymbol("K_SCANCODE_MASK"), v8::Integer::New(SDLK_SCANCODE_MASK));
target->Set(v8::String::NewSymbol("K_KP_AMPERSAND"), v8::Integer::New(SDLK_KP_AMPERSAND));
target->Set(v8::String::NewSymbol("KEYDOWN"), v8::Integer::New(SDL_KEYDOWN));
target->Set(v8::String::NewSymbol("MESSAGEBOX_COLOR_TEXT"), v8::Integer::New(SDL_MESSAGEBOX_COLOR_TEXT));
target->Set(v8::String::NewSymbol("K_CUT"), v8::Integer::New(SDLK_CUT));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_RIGHTSHOULDER"), v8::Integer::New(SDL_CONTROLLER_BUTTON_RIGHTSHOULDER));
target->Set(v8::String::NewSymbol("RENDERER_TARGETTEXTURE"), v8::Integer::New(SDL_RENDERER_TARGETTEXTURE));
target->Set(v8::String::NewSymbol("WINDOW_BORDERLESS"), v8::Integer::New(SDL_WINDOW_BORDERLESS));
target->Set(v8::String::NewSymbol("SCANCODE_DELETE"), v8::Integer::New(SDL_SCANCODE_DELETE));
target->Set(v8::String::NewSymbol("LOG_PRIORITY_WARN"), v8::Integer::New(SDL_LOG_PRIORITY_WARN));
target->Set(v8::String::NewSymbol("K_CRSEL"), v8::Integer::New(SDLK_CRSEL));
target->Set(v8::String::NewSymbol("K_b"), v8::Integer::New(SDLK_b));
target->Set(v8::String::NewSymbol("POWERSTATE_CHARGING"), v8::Integer::New(SDL_POWERSTATE_CHARGING));
target->Set(v8::String::NewSymbol("EFREAD"), v8::Integer::New(SDL_EFREAD));
target->Set(v8::String::NewSymbol("ARRAYORDER_ABGR"), v8::Integer::New(SDL_ARRAYORDER_ABGR));
target->Set(v8::String::NewSymbol("K_AC_SEARCH"), v8::Integer::New(SDLK_AC_SEARCH));
target->Set(v8::String::NewSymbol("ARRAYORDER_RGBA"), v8::Integer::New(SDL_ARRAYORDER_RGBA));
target->Set(v8::String::NewSymbol("K_o"), v8::Integer::New(SDLK_o));
target->Set(v8::String::NewSymbol("K_RETURN"), v8::Integer::New(SDLK_RETURN));
target->Set(v8::String::NewSymbol("K_n"), v8::Integer::New(SDLK_n));
target->Set(v8::String::NewSymbol("K_NUMLOCKCLEAR"), v8::Integer::New(SDLK_NUMLOCKCLEAR));
target->Set(v8::String::NewSymbol("PIXELFORMAT_BGR565"), v8::Integer::New(SDL_PIXELFORMAT_BGR565));
target->Set(v8::String::NewSymbol("PATCHLEVEL"), v8::Integer::New(SDL_PATCHLEVEL));
target->Set(v8::String::NewSymbol("K_KP_BINARY"), v8::Integer::New(SDLK_KP_BINARY));
target->Set(v8::String::NewSymbol("K_QUOTE"), v8::Integer::New(SDLK_QUOTE));
target->Set(v8::String::NewSymbol("CONTROLLER_AXIS_INVALID"), v8::Integer::New(SDL_CONTROLLER_AXIS_INVALID));
target->Set(v8::String::NewSymbol("LOG_PRIORITY_ERROR"), v8::Integer::New(SDL_LOG_PRIORITY_ERROR));
target->Set(v8::String::NewSymbol("MOUSEMOTION"), v8::Integer::New(SDL_MOUSEMOTION));
target->Set(v8::String::NewSymbol("MESSAGEBOX_WARNING"), v8::Integer::New(SDL_MESSAGEBOX_WARNING));
target->Set(v8::String::NewSymbol("BITMAPORDER_1234"), v8::Integer::New(SDL_BITMAPORDER_1234));
target->Set(v8::String::NewSymbol("K_AT"), v8::Integer::New(SDLK_AT));
target->Set(v8::String::NewSymbol("K_AC_REFRESH"), v8::Integer::New(SDLK_AC_REFRESH));
target->Set(v8::String::NewSymbol("SCANCODE_OPER"), v8::Integer::New(SDL_SCANCODE_OPER));
target->Set(v8::String::NewSymbol("FINGERMOTION"), v8::Integer::New(SDL_FINGERMOTION));
target->Set(v8::String::NewSymbol("SCANCODE_POWER"), v8::Integer::New(SDL_SCANCODE_POWER));
target->Set(v8::String::NewSymbol("K_QUESTION"), v8::Integer::New(SDLK_QUESTION));
target->Set(v8::String::NewSymbol("GL_ACCUM_RED_SIZE"), v8::Integer::New(SDL_GL_ACCUM_RED_SIZE));
target->Set(v8::String::NewSymbol("KMOD_LGUI"), v8::Integer::New(KMOD_LGUI));
target->Set(v8::String::NewSymbol("K_KP_POWER"), v8::Integer::New(SDLK_KP_POWER));
target->Set(v8::String::NewSymbol("K_OUT"), v8::Integer::New(SDLK_OUT));
target->Set(v8::String::NewSymbol("WINDOWEVENT_ENTER"), v8::Integer::New(SDL_WINDOWEVENT_ENTER));
target->Set(v8::String::NewSymbol("CONTROLLER_BINDTYPE_BUTTON"), v8::Integer::New(SDL_CONTROLLER_BINDTYPE_BUTTON));
target->Set(v8::String::NewSymbol("INIT_GAMECONTROLLER"), v8::Integer::New(SDL_INIT_GAMECONTROLLER));
target->Set(v8::String::NewSymbol("SYSWMEVENT"), v8::Integer::New(SDL_SYSWMEVENT));
target->Set(v8::String::NewSymbol("SCANCODE_AUDIOPREV"), v8::Integer::New(SDL_SCANCODE_AUDIOPREV));
target->Set(v8::String::NewSymbol("FINGERDOWN"), v8::Integer::New(SDL_FINGERDOWN));
target->Set(v8::String::NewSymbol("INIT_JOYSTICK"), v8::Integer::New(SDL_INIT_JOYSTICK));
target->Set(v8::String::NewSymbol("JOYBUTTONDOWN"), v8::Integer::New(SDL_JOYBUTTONDOWN));
target->Set(v8::String::NewSymbol("K_KP_MEMADD"), v8::Integer::New(SDLK_KP_MEMADD));
target->Set(v8::String::NewSymbol("SCANCODE_KP_AMPERSAND"), v8::Integer::New(SDL_SCANCODE_KP_AMPERSAND));
target->Set(v8::String::NewSymbol("MESSAGEBOX_COLOR_BACKGROUND"), v8::Integer::New(SDL_MESSAGEBOX_COLOR_BACKGROUND));
target->Set(v8::String::NewSymbol("PIXELFORMAT_INDEX1LSB"), v8::Integer::New(SDL_PIXELFORMAT_INDEX1LSB));
target->Set(v8::String::NewSymbol("K_KP_VERTICALBAR"), v8::Integer::New(SDLK_KP_VERTICALBAR));
target->Set(v8::String::NewSymbol("SCANCODE_UNDO"), v8::Integer::New(SDL_SCANCODE_UNDO));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGBA5551"), v8::Integer::New(SDL_PIXELFORMAT_RGBA5551));
target->Set(v8::String::NewSymbol("SCANCODE_INTERNATIONAL3"), v8::Integer::New(SDL_SCANCODE_INTERNATIONAL3));
target->Set(v8::String::NewSymbol("LASTEVENT"), v8::Integer::New(SDL_LASTEVENT));
target->Set(v8::String::NewSymbol("SCANCODE_KP_GREATER"), v8::Integer::New(SDL_SCANCODE_KP_GREATER));
target->Set(v8::String::NewSymbol("K_e"), v8::Integer::New(SDLK_e));
target->Set(v8::String::NewSymbol("SCANCODE_KBDILLUMUP"), v8::Integer::New(SDL_SCANCODE_KBDILLUMUP));
target->Set(v8::String::NewSymbol("K_KP_F"), v8::Integer::New(SDLK_KP_F));
target->Set(v8::String::NewSymbol("PACKEDORDER_ABGR"), v8::Integer::New(SDL_PACKEDORDER_ABGR));
target->Set(v8::String::NewSymbol("RENDERER_SOFTWARE"), v8::Integer::New(SDL_RENDERER_SOFTWARE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_COMMA"), v8::Integer::New(SDL_SCANCODE_KP_COMMA));
target->Set(v8::String::NewSymbol("ARRAYORDER_BGR"), v8::Integer::New(SDL_ARRAYORDER_BGR));
target->Set(v8::String::NewSymbol("K_KP_EQUALSAS400"), v8::Integer::New(SDLK_KP_EQUALSAS400));
target->Set(v8::String::NewSymbol("SCANCODE_KP_DBLVERTICALBAR"), v8::Integer::New(SDL_SCANCODE_KP_DBLVERTICALBAR));
target->Set(v8::String::NewSymbol("SCANCODE_RIGHT"), v8::Integer::New(SDL_SCANCODE_RIGHT));
target->Set(v8::String::NewSymbol("LASTERROR"), v8::Integer::New(SDL_LASTERROR));
target->Set(v8::String::NewSymbol("K_UNDERSCORE"), v8::Integer::New(SDLK_UNDERSCORE));
target->Set(v8::String::NewSymbol("ARRAYORDER_RGB"), v8::Integer::New(SDL_ARRAYORDER_RGB));
target->Set(v8::String::NewSymbol("WINDOWEVENT_RESIZED"), v8::Integer::New(SDL_WINDOWEVENT_RESIZED));
target->Set(v8::String::NewSymbol("K_KBDILLUMTOGGLE"), v8::Integer::New(SDLK_KBDILLUMTOGGLE));
target->Set(v8::String::NewSymbol("MESSAGEBOX_INFORMATION"), v8::Integer::New(SDL_MESSAGEBOX_INFORMATION));
target->Set(v8::String::NewSymbol("GL_STENCIL_SIZE"), v8::Integer::New(SDL_GL_STENCIL_SIZE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_LEFTBRACE"), v8::Integer::New(SDL_SCANCODE_KP_LEFTBRACE));
target->Set(v8::String::NewSymbol("WINDOW_FOREIGN"), v8::Integer::New(SDL_WINDOW_FOREIGN));
target->Set(v8::String::NewSymbol("SCANCODE_AC_BOOKMARKS"), v8::Integer::New(SDL_SCANCODE_AC_BOOKMARKS));
target->Set(v8::String::NewSymbol("GL_RETAINED_BACKING"), v8::Integer::New(SDL_GL_RETAINED_BACKING));
target->Set(v8::String::NewSymbol("K_KP_HEXADECIMAL"), v8::Integer::New(SDLK_KP_HEXADECIMAL));
target->Set(v8::String::NewSymbol("WINDOW_MAXIMIZED"), v8::Integer::New(SDL_WINDOW_MAXIMIZED));
target->Set(v8::String::NewSymbol("SCANCODE_PRIOR"), v8::Integer::New(SDL_SCANCODE_PRIOR));
target->Set(v8::String::NewSymbol("K_KP_PLUSMINUS"), v8::Integer::New(SDLK_KP_PLUSMINUS));
target->Set(v8::String::NewSymbol("JOYBUTTONUP"), v8::Integer::New(SDL_JOYBUTTONUP));
target->Set(v8::String::NewSymbol("AUDIO_PLAYING"), v8::Integer::New(SDL_AUDIO_PLAYING));
target->Set(v8::String::NewSymbol("DOLLARRECORD"), v8::Integer::New(SDL_DOLLARRECORD));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGB24"), v8::Integer::New(SDL_PIXELFORMAT_RGB24));
target->Set(v8::String::NewSymbol("INIT_AUDIO"), v8::Integer::New(SDL_INIT_AUDIO));
target->Set(v8::String::NewSymbol("K_KP_A"), v8::Integer::New(SDLK_KP_A));
target->Set(v8::String::NewSymbol("POWERSTATE_ON_BATTERY"), v8::Integer::New(SDL_POWERSTATE_ON_BATTERY));
target->Set(v8::String::NewSymbol("K_CURRENCYSUBUNIT"), v8::Integer::New(SDLK_CURRENCYSUBUNIT));
target->Set(v8::String::NewSymbol("ASSERTION_ALWAYS_IGNORE"), v8::Integer::New(SDL_ASSERTION_ALWAYS_IGNORE));
target->Set(v8::String::NewSymbol("TEXTINPUT"), v8::Integer::New(SDL_TEXTINPUT));
target->Set(v8::String::NewSymbol("K_KP_ENTER"), v8::Integer::New(SDLK_KP_ENTER));
target->Set(v8::String::NewSymbol("SCANCODE_KBDILLUMDOWN"), v8::Integer::New(SDL_SCANCODE_KBDILLUMDOWN));
target->Set(v8::String::NewSymbol("SCANCODE_KP_EQUALS"), v8::Integer::New(SDL_SCANCODE_KP_EQUALS));
target->Set(v8::String::NewSymbol("K_AUDIOMUTE"), v8::Integer::New(SDLK_AUDIOMUTE));
target->Set(v8::String::NewSymbol("GL_CONTEXT_FORWARD_COMPATIBLE_FLAG"), v8::Integer::New(SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG));
target->Set(v8::String::NewSymbol("SCANCODE_KP_PLUS"), v8::Integer::New(SDL_SCANCODE_KP_PLUS));
target->Set(v8::String::NewSymbol("CONTROLLER_BUTTON_DPAD_LEFT"), v8::Integer::New(SDL_CONTROLLER_BUTTON_DPAD_LEFT));
target->Set(v8::String::NewSymbol("TOUCHBUTTONUP"), v8::Integer::New(SDL_TOUCHBUTTONUP));
target->Set(v8::String::NewSymbol("SCANCODE_KP_000"), v8::Integer::New(SDL_SCANCODE_KP_000));
target->Set(v8::String::NewSymbol("INIT_NOPARACHUTE"), v8::Integer::New(SDL_INIT_NOPARACHUTE));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGBA4444"), v8::Integer::New(SDL_PIXELFORMAT_RGBA4444));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_AUDIO"), v8::Integer::New(SDL_LOG_CATEGORY_AUDIO));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_TEST"), v8::Integer::New(SDL_LOG_CATEGORY_TEST));
target->Set(v8::String::NewSymbol("K_GREATER"), v8::Integer::New(SDLK_GREATER));
target->Set(v8::String::NewSymbol("SCANCODE_KP_MEMSTORE"), v8::Integer::New(SDL_SCANCODE_KP_MEMSTORE));
target->Set(v8::String::NewSymbol("WINDOWEVENT_SHOWN"), v8::Integer::New(SDL_WINDOWEVENT_SHOWN));
target->Set(v8::String::NewSymbol("CLIPBOARDUPDATE"), v8::Integer::New(SDL_CLIPBOARDUPDATE));
target->Set(v8::String::NewSymbol("BUTTON_LEFT"), v8::Integer::New(SDL_BUTTON_LEFT));
target->Set(v8::String::NewSymbol("SCANCODE_LSHIFT"), v8::Integer::New(SDL_SCANCODE_LSHIFT));
target->Set(v8::String::NewSymbol("GL_ACCELERATED_VISUAL"), v8::Integer::New(SDL_GL_ACCELERATED_VISUAL));
target->Set(v8::String::NewSymbol("DROPFILE"), v8::Integer::New(SDL_DROPFILE));
target->Set(v8::String::NewSymbol("WINDOW_FULLSCREEN"), v8::Integer::New(SDL_WINDOW_FULLSCREEN));
target->Set(v8::String::NewSymbol("K_COMMA"), v8::Integer::New(SDLK_COMMA));
target->Set(v8::String::NewSymbol("SCANCODE_KP_AT"), v8::Integer::New(SDL_SCANCODE_KP_AT));
target->Set(v8::String::NewSymbol("K_KP_BACKSPACE"), v8::Integer::New(SDLK_KP_BACKSPACE));
target->Set(v8::String::NewSymbol("K_MENU"), v8::Integer::New(SDLK_MENU));
target->Set(v8::String::NewSymbol("K_AC_FORWARD"), v8::Integer::New(SDLK_AC_FORWARD));
target->Set(v8::String::NewSymbol("AUDIO_ALLOW_CHANNELS_CHANGE"), v8::Integer::New(SDL_AUDIO_ALLOW_CHANNELS_CHANGE));
target->Set(v8::String::NewSymbol("K_3"), v8::Integer::New(SDLK_3));
target->Set(v8::String::NewSymbol("K_KP_XOR"), v8::Integer::New(SDLK_KP_XOR));
target->Set(v8::String::NewSymbol("GL_ALPHA_SIZE"), v8::Integer::New(SDL_GL_ALPHA_SIZE));
target->Set(v8::String::NewSymbol("ASSERTION_IGNORE"), v8::Integer::New(SDL_ASSERTION_IGNORE));
target->Set(v8::String::NewSymbol("SCANCODE_END"), v8::Integer::New(SDL_SCANCODE_END));
target->Set(v8::String::NewSymbol("SCANCODE_SYSREQ"), v8::Integer::New(SDL_SCANCODE_SYSREQ));
target->Set(v8::String::NewSymbol("TEXTUREACCESS_STATIC"), v8::Integer::New(SDL_TEXTUREACCESS_STATIC));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGBX8888"), v8::Integer::New(SDL_PIXELFORMAT_RGBX8888));
target->Set(v8::String::NewSymbol("WINDOWEVENT_EXPOSED"), v8::Integer::New(SDL_WINDOWEVENT_EXPOSED));
target->Set(v8::String::NewSymbol("K_POWER"), v8::Integer::New(SDLK_POWER));
target->Set(v8::String::NewSymbol("SCANCODE_KP_POWER"), v8::Integer::New(SDL_SCANCODE_KP_POWER));
target->Set(v8::String::NewSymbol("PIXELTYPE_ARRAYU32"), v8::Integer::New(SDL_PIXELTYPE_ARRAYU32));
target->Set(v8::String::NewSymbol("K_9"), v8::Integer::New(SDLK_9));
target->Set(v8::String::NewSymbol("TEXTUREACCESS_TARGET"), v8::Integer::New(SDL_TEXTUREACCESS_TARGET));
target->Set(v8::String::NewSymbol("ASSERTION_ABORT"), v8::Integer::New(SDL_ASSERTION_ABORT));
target->Set(v8::String::NewSymbol("KMOD_RCTRL"), v8::Integer::New(KMOD_RCTRL));
target->Set(v8::String::NewSymbol("K_VOLUMEDOWN"), v8::Integer::New(SDLK_VOLUMEDOWN));
target->Set(v8::String::NewSymbol("K_KP_DIVIDE"), v8::Integer::New(SDLK_KP_DIVIDE));
target->Set(v8::String::NewSymbol("GL_CONTEXT_PROFILE_CORE"), v8::Integer::New(SDL_GL_CONTEXT_PROFILE_CORE));
target->Set(v8::String::NewSymbol("SCANCODE_AUDIOSTOP"), v8::Integer::New(SDL_SCANCODE_AUDIOSTOP));
target->Set(v8::String::NewSymbol("BIG_ENDIAN"), v8::Integer::New(SDL_BIG_ENDIAN));
target->Set(v8::String::NewSymbol("GL_CONTEXT_DEBUG_FLAG"), v8::Integer::New(SDL_GL_CONTEXT_DEBUG_FLAG));
target->Set(v8::String::NewSymbol("CONTROLLERBUTTONDOWN"), v8::Integer::New(SDL_CONTROLLERBUTTONDOWN));
target->Set(v8::String::NewSymbol("PIXELTYPE_PACKED32"), v8::Integer::New(SDL_PIXELTYPE_PACKED32));
target->Set(v8::String::NewSymbol("WINDOWEVENT_LEAVE"), v8::Integer::New(SDL_WINDOWEVENT_LEAVE));
target->Set(v8::String::NewSymbol("K_KP_MEMCLEAR"), v8::Integer::New(SDLK_KP_MEMCLEAR));
target->Set(v8::String::NewSymbol("SCANCODE_ALTERASE"), v8::Integer::New(SDL_SCANCODE_ALTERASE));
target->Set(v8::String::NewSymbol("AUDIO_MASK_SIGNED"), v8::Integer::New(SDL_AUDIO_MASK_SIGNED));
target->Set(v8::String::NewSymbol("PIXELTYPE_INDEX8"), v8::Integer::New(SDL_PIXELTYPE_INDEX8));
target->Set(v8::String::NewSymbol("HINT_OVERRIDE"), v8::Integer::New(SDL_HINT_OVERRIDE));
target->Set(v8::String::NewSymbol("ADDEVENT"), v8::Integer::New(SDL_ADDEVENT));
target->Set(v8::String::NewSymbol("PIXELTYPE_INDEX4"), v8::Integer::New(SDL_PIXELTYPE_INDEX4));
target->Set(v8::String::NewSymbol("PIXELTYPE_INDEX1"), v8::Integer::New(SDL_PIXELTYPE_INDEX1));
target->Set(v8::String::NewSymbol("K_LSHIFT"), v8::Integer::New(SDLK_LSHIFT));
target->Set(v8::String::NewSymbol("GL_CONTEXT_RESET_ISOLATION_FLAG"), v8::Integer::New(SDL_GL_CONTEXT_RESET_ISOLATION_FLAG));
target->Set(v8::String::NewSymbol("WINDOWPOS_CENTERED_MASK"), v8::Integer::New(SDL_WINDOWPOS_CENTERED_MASK));
target->Set(v8::String::NewSymbol("K_KP_LEFTBRACE"), v8::Integer::New(SDLK_KP_LEFTBRACE));
target->Set(v8::String::NewSymbol("SCANCODE_INTERNATIONAL2"), v8::Integer::New(SDL_SCANCODE_INTERNATIONAL2));
target->Set(v8::String::NewSymbol("PACKEDLAYOUT_332"), v8::Integer::New(SDL_PACKEDLAYOUT_332));
target->Set(v8::String::NewSymbol("SCANCODE_INTERNATIONAL1"), v8::Integer::New(SDL_SCANCODE_INTERNATIONAL1));
target->Set(v8::String::NewSymbol("SCANCODE_INTERNATIONAL6"), v8::Integer::New(SDL_SCANCODE_INTERNATIONAL6));
target->Set(v8::String::NewSymbol("SCANCODE_INTERNATIONAL7"), v8::Integer::New(SDL_SCANCODE_INTERNATIONAL7));
target->Set(v8::String::NewSymbol("SCANCODE_INTERNATIONAL4"), v8::Integer::New(SDL_SCANCODE_INTERNATIONAL4));
target->Set(v8::String::NewSymbol("SCANCODE_INTERNATIONAL5"), v8::Integer::New(SDL_SCANCODE_INTERNATIONAL5));
target->Set(v8::String::NewSymbol("GL_CONTEXT_PROFILE_ES"), v8::Integer::New(SDL_GL_CONTEXT_PROFILE_ES));
target->Set(v8::String::NewSymbol("SCANCODE_INTERNATIONAL8"), v8::Integer::New(SDL_SCANCODE_INTERNATIONAL8));
target->Set(v8::String::NewSymbol("SCANCODE_INTERNATIONAL9"), v8::Integer::New(SDL_SCANCODE_INTERNATIONAL9));
target->Set(v8::String::NewSymbol("SCANCODE_CLEAR"), v8::Integer::New(SDL_SCANCODE_CLEAR));
target->Set(v8::String::NewSymbol("LOG_CATEGORY_RESERVED7"), v8::Integer::New(SDL_LOG_CATEGORY_RESERVED7));
target->Set(v8::String::NewSymbol("TRUE"), v8::Integer::New(SDL_TRUE));
target->Set(v8::String::NewSymbol("SCANCODE_KP_EQUALSAS400"), v8::Integer::New(SDL_SCANCODE_KP_EQUALSAS400));
target->Set(v8::String::NewSymbol("K_KP_DBLAMPERSAND"), v8::Integer::New(SDLK_KP_DBLAMPERSAND));
target->Set(v8::String::NewSymbol("PIXELFORMAT_RGB332"), v8::Integer::New(SDL_PIXELFORMAT_RGB332));
#ifdef SDL_JOYSTICK_NDS
target->Set(v8::String::NewSymbol("JOYSTICK_NDS"), v8::Integer::New(SDL_JOYSTICK_NDS));
#endif
#ifdef SDL_POWER_HARDWIRED
target->Set(v8::String::NewSymbol("POWER_HARDWIRED"), v8::Integer::New(SDL_POWER_HARDWIRED));
#endif
#ifdef SDL_POWER_MACOSX
target->Set(v8::String::NewSymbol("POWER_MACOSX"), v8::Integer::New(SDL_POWER_MACOSX));
#endif
#ifdef SDL_AUDIO_DRIVER_NAS
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_NAS"), v8::Integer::New(SDL_AUDIO_DRIVER_NAS));
#endif
#ifdef SDL_RENDER_DISABLED
target->Set(v8::String::NewSymbol("RENDER_DISABLED"), v8::Integer::New(SDL_RENDER_DISABLED));
#endif
#ifdef SDL_VIDEO_OPENGL_GLX
target->Set(v8::String::NewSymbol("VIDEO_OPENGL_GLX"), v8::Integer::New(SDL_VIDEO_OPENGL_GLX));
#endif
#ifdef SDL_POWER_NINTENDODS
target->Set(v8::String::NewSymbol("POWER_NINTENDODS"), v8::Integer::New(SDL_POWER_NINTENDODS));
#endif
#ifdef SDL_THREAD_PTHREAD_RECURSIVE_MUTEX
target->Set(v8::String::NewSymbol("THREAD_PTHREAD_RECURSIVE_MUTEX"), v8::Integer::New(SDL_THREAD_PTHREAD_RECURSIVE_MUTEX));
#endif
#ifdef SDL_LOADSO_DLOPEN
target->Set(v8::String::NewSymbol("LOADSO_DLOPEN"), v8::Integer::New(SDL_LOADSO_DLOPEN));
#endif
#ifdef SDL_VIDEO_DRIVER_BWINDOW
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_BWINDOW"), v8::Integer::New(SDL_VIDEO_DRIVER_BWINDOW));
#endif
#ifdef SDL_JOYSTICK_USBHID
target->Set(v8::String::NewSymbol("JOYSTICK_USBHID"), v8::Integer::New(SDL_JOYSTICK_USBHID));
#endif
#ifdef SDL_LOADSO_WINDOWS
target->Set(v8::String::NewSymbol("LOADSO_WINDOWS"), v8::Integer::New(SDL_LOADSO_WINDOWS));
#endif
#ifdef SDL_JOYSTICK_DINPUT
target->Set(v8::String::NewSymbol("JOYSTICK_DINPUT"), v8::Integer::New(SDL_JOYSTICK_DINPUT));
#endif
#ifdef SDL_AUDIO_DRIVER_OSS_SOUNDCARD_H
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_OSS_SOUNDCARD_H"), v8::Integer::New(SDL_AUDIO_DRIVER_OSS_SOUNDCARD_H));
#endif
#ifdef SDL_AUDIO_DRIVER_ARTS
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_ARTS"), v8::Integer::New(SDL_AUDIO_DRIVER_ARTS));
#endif
#ifdef SDL_VIDEO_OPENGL_ES
target->Set(v8::String::NewSymbol("VIDEO_OPENGL_ES"), v8::Integer::New(SDL_VIDEO_OPENGL_ES));
#endif
#ifdef SDL_AUDIO_DRIVER_OSS
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_OSS"), v8::Integer::New(SDL_AUDIO_DRIVER_OSS));
#endif
#ifdef SDL_VIDEO_OPENGL
target->Set(v8::String::NewSymbol("VIDEO_OPENGL"), v8::Integer::New(SDL_VIDEO_OPENGL));
#endif
#ifdef SDL_AUDIO_DRIVER_DISK
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_DISK"), v8::Integer::New(SDL_AUDIO_DRIVER_DISK));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_XCURSOR
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_XCURSOR"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_XCURSOR));
#endif
#ifdef SDL_CPUINFO_DISABLED
target->Set(v8::String::NewSymbol("CPUINFO_DISABLED"), v8::Integer::New(SDL_CPUINFO_DISABLED));
#endif
#ifdef SDL_VIDEO_DRIVER_COCOA
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_COCOA"), v8::Integer::New(SDL_VIDEO_DRIVER_COCOA));
#endif
#ifdef SDL_VIDEO_DRIVER_DUMMY
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_DUMMY"), v8::Integer::New(SDL_VIDEO_DRIVER_DUMMY));
#endif
#ifdef SDL_VIDEO_DISABLED
target->Set(v8::String::NewSymbol("VIDEO_DISABLED"), v8::Integer::New(SDL_VIDEO_DISABLED));
#endif
#ifdef SDL_LOADSO_DISABLED
target->Set(v8::String::NewSymbol("LOADSO_DISABLED"), v8::Integer::New(SDL_LOADSO_DISABLED));
#endif
#ifdef SDL_THREAD_BEOS
target->Set(v8::String::NewSymbol("THREAD_BEOS"), v8::Integer::New(SDL_THREAD_BEOS));
#endif
#ifdef SDL_VIDEO_DRIVER_DIRECTFB
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_DIRECTFB"), v8::Integer::New(SDL_VIDEO_DRIVER_DIRECTFB));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_CONST_PARAM_XEXTADDDISPLAY
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_CONST_PARAM_XEXTADDDISPLAY"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_CONST_PARAM_XEXTADDDISPLAY));
#endif
#ifdef SDL_AUDIO_DRIVER_PAUDIO
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_PAUDIO"), v8::Integer::New(SDL_AUDIO_DRIVER_PAUDIO));
#endif
#ifdef SDL_JOYSTICK_USBHID_MACHINE_JOYSTICK_H
target->Set(v8::String::NewSymbol("JOYSTICK_USBHID_MACHINE_JOYSTICK_H"), v8::Integer::New(SDL_JOYSTICK_USBHID_MACHINE_JOYSTICK_H));
#endif
#ifdef SDL_THREAD_PTHREAD_RECURSIVE_MUTEX_NP
target->Set(v8::String::NewSymbol("THREAD_PTHREAD_RECURSIVE_MUTEX_NP"), v8::Integer::New(SDL_THREAD_PTHREAD_RECURSIVE_MUTEX_NP));
#endif
#ifdef SDL_JOYSTICK_DUMMY
target->Set(v8::String::NewSymbol("JOYSTICK_DUMMY"), v8::Integer::New(SDL_JOYSTICK_DUMMY));
#endif
#ifdef SDL_AUDIO_DRIVER_ESD
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_ESD"), v8::Integer::New(SDL_AUDIO_DRIVER_ESD));
#endif
#ifdef SDL_VIDEO_DRIVER_X11
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11"), v8::Integer::New(SDL_VIDEO_DRIVER_X11));
#endif
#ifdef SDL_THREADS_DISABLED
target->Set(v8::String::NewSymbol("THREADS_DISABLED"), v8::Integer::New(SDL_THREADS_DISABLED));
#endif
#ifdef SDL_HAPTIC_IOKIT
target->Set(v8::String::NewSymbol("HAPTIC_IOKIT"), v8::Integer::New(SDL_HAPTIC_IOKIT));
#endif
#ifdef SDL_AUDIO_DRIVER_XAUDIO2
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_XAUDIO2"), v8::Integer::New(SDL_AUDIO_DRIVER_XAUDIO2));
#endif
#ifdef SDL_AUDIO_DRIVER_NDS
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_NDS"), v8::Integer::New(SDL_AUDIO_DRIVER_NDS));
#endif
#ifdef SDL_VIDEO_RENDER_OGL_ES
target->Set(v8::String::NewSymbol("VIDEO_RENDER_OGL_ES"), v8::Integer::New(SDL_VIDEO_RENDER_OGL_ES));
#endif
#ifdef SDL_INPUT_LINUXEV
target->Set(v8::String::NewSymbol("INPUT_LINUXEV"), v8::Integer::New(SDL_INPUT_LINUXEV));
#endif
#ifdef SDL_EVENTS_DISABLED
target->Set(v8::String::NewSymbol("EVENTS_DISABLED"), v8::Integer::New(SDL_EVENTS_DISABLED));
#endif
#ifdef SDL_THREAD_PTHREAD
target->Set(v8::String::NewSymbol("THREAD_PTHREAD"), v8::Integer::New(SDL_THREAD_PTHREAD));
#endif
#ifdef SDL_AUDIO_DRIVER_WINMM
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_WINMM"), v8::Integer::New(SDL_AUDIO_DRIVER_WINMM));
#endif
#ifdef SDL_AUDIO_DRIVER_PULSEAUDIO
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_PULSEAUDIO"), v8::Integer::New(SDL_AUDIO_DRIVER_PULSEAUDIO));
#endif
#ifdef SDL_THREAD_WINDOWS
target->Set(v8::String::NewSymbol("THREAD_WINDOWS"), v8::Integer::New(SDL_THREAD_WINDOWS));
#endif
#ifdef SDL_FILE_DISABLED
target->Set(v8::String::NewSymbol("FILE_DISABLED"), v8::Integer::New(SDL_FILE_DISABLED));
#endif
#ifdef SDL_AUDIO_DRIVER_DUMMY
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_DUMMY"), v8::Integer::New(SDL_AUDIO_DRIVER_DUMMY));
#endif
#ifdef SDL_JOYSTICK_WINMM
target->Set(v8::String::NewSymbol("JOYSTICK_WINMM"), v8::Integer::New(SDL_JOYSTICK_WINMM));
#endif
#ifdef SDL_TIMER_DUMMY
target->Set(v8::String::NewSymbol("TIMER_DUMMY"), v8::Integer::New(SDL_TIMER_DUMMY));
#endif
#ifdef SDL_ATOMIC_DISABLED
target->Set(v8::String::NewSymbol("ATOMIC_DISABLED"), v8::Integer::New(SDL_ATOMIC_DISABLED));
#endif
#ifdef SDL_TIMER_WINDOWS
target->Set(v8::String::NewSymbol("TIMER_WINDOWS"), v8::Integer::New(SDL_TIMER_WINDOWS));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_XRANDR
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_XRANDR"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_XRANDR));
#endif
#ifdef SDL_TIMER_BEOS
target->Set(v8::String::NewSymbol("TIMER_BEOS"), v8::Integer::New(SDL_TIMER_BEOS));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS));
#endif
#ifdef SDL_INPUT_TSLIB
target->Set(v8::String::NewSymbol("INPUT_TSLIB"), v8::Integer::New(SDL_INPUT_TSLIB));
#endif
#ifdef SDL_AUDIO_DRIVER_FUSIONSOUND
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_FUSIONSOUND"), v8::Integer::New(SDL_AUDIO_DRIVER_FUSIONSOUND));
#endif
#ifdef SDL_VIDEO_DRIVER_NDS
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_NDS"), v8::Integer::New(SDL_VIDEO_DRIVER_NDS));
#endif
#ifdef SDL_VIDEO_RENDER_OGL
target->Set(v8::String::NewSymbol("VIDEO_RENDER_OGL"), v8::Integer::New(SDL_VIDEO_RENDER_OGL));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_XINERAMA
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_XINERAMA"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_XINERAMA));
#endif
#ifdef SDL_AUDIO_DRIVER_COREAUDIO
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_COREAUDIO"), v8::Integer::New(SDL_AUDIO_DRIVER_COREAUDIO));
#endif
#ifdef SDL_HAPTIC_DISABLED
target->Set(v8::String::NewSymbol("HAPTIC_DISABLED"), v8::Integer::New(SDL_HAPTIC_DISABLED));
#endif
#ifdef SDL_VIDEO_RENDER_DIRECTFB
target->Set(v8::String::NewSymbol("VIDEO_RENDER_DIRECTFB"), v8::Integer::New(SDL_VIDEO_RENDER_DIRECTFB));
#endif
#ifdef SDL_POWER_DISABLED
target->Set(v8::String::NewSymbol("POWER_DISABLED"), v8::Integer::New(SDL_POWER_DISABLED));
#endif
#ifdef SDL_VIDEO_OPENGL_WGL
target->Set(v8::String::NewSymbol("VIDEO_OPENGL_WGL"), v8::Integer::New(SDL_VIDEO_OPENGL_WGL));
#endif
#ifdef SDL_JOYSTICK_IOKIT
target->Set(v8::String::NewSymbol("JOYSTICK_IOKIT"), v8::Integer::New(SDL_JOYSTICK_IOKIT));
#endif
#ifdef SDL_LOADSO_BEOS
target->Set(v8::String::NewSymbol("LOADSO_BEOS"), v8::Integer::New(SDL_LOADSO_BEOS));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_XINPUT2
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_XINPUT2"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_XINPUT2));
#endif
#ifdef SDL_TIMER_UNIX
target->Set(v8::String::NewSymbol("TIMER_UNIX"), v8::Integer::New(SDL_TIMER_UNIX));
#endif
#ifdef SDL_JOYSTICK_BEOS
target->Set(v8::String::NewSymbol("JOYSTICK_BEOS"), v8::Integer::New(SDL_JOYSTICK_BEOS));
#endif
#ifdef SDL_DEFAULT_ASSERT_LEVEL
target->Set(v8::String::NewSymbol("DEFAULT_ASSERT_LEVEL"), v8::Integer::New(SDL_DEFAULT_ASSERT_LEVEL));
#endif
#ifdef SDL_AUDIO_DRIVER_QSA
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_QSA"), v8::Integer::New(SDL_AUDIO_DRIVER_QSA));
#endif
#ifdef SDL_POWER_WINDOWS
target->Set(v8::String::NewSymbol("POWER_WINDOWS"), v8::Integer::New(SDL_POWER_WINDOWS));
#endif
#ifdef SDL_ASSEMBLY_ROUTINES
target->Set(v8::String::NewSymbol("ASSEMBLY_ROUTINES"), v8::Integer::New(SDL_ASSEMBLY_ROUTINES));
#endif
#ifdef SDL_JOYSTICK_DISABLED
target->Set(v8::String::NewSymbol("JOYSTICK_DISABLED"), v8::Integer::New(SDL_JOYSTICK_DISABLED));
#endif
#ifdef SDL_AUDIO_DRIVER_ALSA
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_ALSA"), v8::Integer::New(SDL_AUDIO_DRIVER_ALSA));
#endif
#ifdef SDL_POWER_LINUX
target->Set(v8::String::NewSymbol("POWER_LINUX"), v8::Integer::New(SDL_POWER_LINUX));
#endif
#ifdef SDL_HAPTIC_DINPUT
target->Set(v8::String::NewSymbol("HAPTIC_DINPUT"), v8::Integer::New(SDL_HAPTIC_DINPUT));
#endif
#ifdef SDL_VIDEO_OPENGL_BGL
target->Set(v8::String::NewSymbol("VIDEO_OPENGL_BGL"), v8::Integer::New(SDL_VIDEO_OPENGL_BGL));
#endif
#ifdef SDL_LOADSO_DUMMY
target->Set(v8::String::NewSymbol("LOADSO_DUMMY"), v8::Integer::New(SDL_LOADSO_DUMMY));
#endif
#ifdef SDL_AUDIO_DRIVER_DSOUND
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_DSOUND"), v8::Integer::New(SDL_AUDIO_DRIVER_DSOUND));
#endif
#ifdef SDL_AUDIO_DRIVER_BSD
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_BSD"), v8::Integer::New(SDL_AUDIO_DRIVER_BSD));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH));
#endif
#ifdef SDL_LOADSO_LDG
target->Set(v8::String::NewSymbol("LOADSO_LDG"), v8::Integer::New(SDL_LOADSO_LDG));
#endif
#ifdef SDL_THREAD_NDS
target->Set(v8::String::NewSymbol("THREAD_NDS"), v8::Integer::New(SDL_THREAD_NDS));
#endif
#ifdef SDL_AUDIO_DRIVER_SUNAUDIO
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_SUNAUDIO"), v8::Integer::New(SDL_AUDIO_DRIVER_SUNAUDIO));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_XSHAPE
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_XSHAPE"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_XSHAPE));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_XVIDMODE
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_XVIDMODE"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_XVIDMODE));
#endif
#ifdef SDL_TIMERS_DISABLED
target->Set(v8::String::NewSymbol("TIMERS_DISABLED"), v8::Integer::New(SDL_TIMERS_DISABLED));
#endif
#ifdef SDL_TIMER_NDS
target->Set(v8::String::NewSymbol("TIMER_NDS"), v8::Integer::New(SDL_TIMER_NDS));
#endif
#ifdef SDL_AUDIO_DRIVER_BEOSAUDIO
target->Set(v8::String::NewSymbol("AUDIO_DRIVER_BEOSAUDIO"), v8::Integer::New(SDL_AUDIO_DRIVER_BEOSAUDIO));
#endif
#ifdef SDL_POWER_BEOS
target->Set(v8::String::NewSymbol("POWER_BEOS"), v8::Integer::New(SDL_POWER_BEOS));
#endif
#ifdef SDL_VIDEO_RENDER_OGL_ES2
target->Set(v8::String::NewSymbol("VIDEO_RENDER_OGL_ES2"), v8::Integer::New(SDL_VIDEO_RENDER_OGL_ES2));
#endif
#ifdef SDL_VIDEO_OPENGL_CGL
target->Set(v8::String::NewSymbol("VIDEO_OPENGL_CGL"), v8::Integer::New(SDL_VIDEO_OPENGL_CGL));
#endif
#ifdef SDL_ALTIVEC_BLITTERS
target->Set(v8::String::NewSymbol("ALTIVEC_BLITTERS"), v8::Integer::New(SDL_ALTIVEC_BLITTERS));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM));
#endif
#ifdef SDL_VIDEO_OPENGL_OSMESA
target->Set(v8::String::NewSymbol("VIDEO_OPENGL_OSMESA"), v8::Integer::New(SDL_VIDEO_OPENGL_OSMESA));
#endif
#ifdef SDL_HAPTIC_LINUX
target->Set(v8::String::NewSymbol("HAPTIC_LINUX"), v8::Integer::New(SDL_HAPTIC_LINUX));
#endif
#ifdef SDL_VIDEO_DRIVER_X11_XSCRNSAVER
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_X11_XSCRNSAVER"), v8::Integer::New(SDL_VIDEO_DRIVER_X11_XSCRNSAVER));
#endif
#ifdef SDL_AUDIO_DISABLED
target->Set(v8::String::NewSymbol("AUDIO_DISABLED"), v8::Integer::New(SDL_AUDIO_DISABLED));
#endif
#ifdef SDL_VIDEO_DRIVER_WINDOWS
target->Set(v8::String::NewSymbol("VIDEO_DRIVER_WINDOWS"), v8::Integer::New(SDL_VIDEO_DRIVER_WINDOWS));
#endif
#ifdef SDL_HAPTIC_DUMMY
target->Set(v8::String::NewSymbol("HAPTIC_DUMMY"), v8::Integer::New(SDL_HAPTIC_DUMMY));
#endif
#ifdef SDL_VIDEO_RENDER_D3D
target->Set(v8::String::NewSymbol("VIDEO_RENDER_D3D"), v8::Integer::New(SDL_VIDEO_RENDER_D3D));
#endif
#ifdef SDL_JOYSTICK_LINUX
target->Set(v8::String::NewSymbol("JOYSTICK_LINUX"), v8::Integer::New(SDL_JOYSTICK_LINUX));
#endif
}
